.gitmodules, puppet/modules/jenkins_job_builder/manifests/init.pp
This is so we can use things like http://www.larrycaiyu.com/blog/2014/01/14/extend-jenkins-job-builder/ on our fork of JJB to add plugins we use in Jenkins.
=> Switch JJB to a git clone, for ease of coding new plugin xml changes

puppet/modules/jenkins_job_builder/manifests/init.pp
Seems to work:
```
[root@centos1010 foreman-infra.greg]# puppet apply -vt --modulepath /root/foreman-infra.greg/puppet/modules/ /root/test.pp  --no-noop
Info: Loading facts
Notice: Compiled catalog for centos1010.sapphire.elysium.emeraldreverie.org in environment production in 1.90 seconds
Info: Applying configuration version '1426249242'
Notice: Finished catalog run in 16.03 seconds
[root@centos1010 foreman-infra.greg]# date 03130235
Fri Mar 13 02:35:00 UTC 2015
[root@centos1010 foreman-infra.greg]# puppet apply -vt --modulepath /root/foreman-infra.greg/puppet/modules/ /root/test.pp  --no-noop
Info: Loading facts
Notice: Compiled catalog for centos1010.sapphire.elysium.emeraldreverie.org in environment production in 1.92 seconds
Info: Applying configuration version '1426214104'
Notice: …
```
=> Add scheduled jjb run for reverting manual changes

puppet/modules/jenkins_job_builder/files/config/yaml/scm/katello.org.yaml
JJB doesn't like the bare / it seems:
```
yaml.scanner.ScannerError: while scanning an alias
in "/etc/jenkins_jobs/config/yaml/scm/katello.org.yaml", line 9, column 13
expected alphabetic or numeric character, but found '/'
in "/etc/jenkins_jobs/config/yaml/scm/katello.org.yaml", line 9, column 14
```
=> [jjb] Fix formatting in katello.org SCM yaml

puppet/modules/jenkins_job_builder/files/config/scripts/systest_foreman.sh
The "jessie" repo was empty anyway (besides puppetlabs-release), and "testing"
repos were filled. However, now even puppetlabs-release was pulled from
apt.puppetlabs.com index, so fb-install-plpuppet.bats would always fail.
=> don't use PL repo for Debian/jessie

puppet/modules/slave/manifests/init.pp
What I'd like to achieve: __Installing OpenSCAP on the slave servers.__
How: Adding openscap repo data to the slave puppet.
~~Please note related PR: https://github.com/theforeman/puppet-foreman/pull/326
Which will require a version bump for foreman-infra/modules/foreman submodule.~~
=> Add openscap repo data and install openscap

puppet/modules/debian/manifests/init.pp
This past week we've been seeing build failures on Debian OSes connecting to the .de mirror from our slaves which are all in the US.  142df89 already changed Ubuntu, so this changes Debian too.
=> Change Debian mirrors to US for proximity to builders

puppet/modules/apache/manifests/debian.pp, puppet/modules/apache/manifests/redhat.pp, puppet/modules/apache/manifests/vhost.pp, puppet/modules/apache/templates/vhost-ssl.erb, puppet/modules/apache/templates/vhost.erb
Current vhost logs are under /var/www/vhosts/*/logs which isn't
accessible to logrotate under SELinux.  Rather than add custom policy
or customise the labelling, move them to the usual /var/log/ location.
--
Should fix lack of logrotation on our web server now.  Please just review, I'll merge it as I'll probably move the existing log files over so we don't lose anything.
=> Move Apache vhost logs to /var/log

.gitmodules, puppet/modules/deploy/manifests/init.pp, puppet/modules/freight/manifests/user.pp, puppet/modules/web/manifests/init.pp
Two new slaves are deployed on OpenStack with floating IPs, which
aren't visible to the slave's networking stack or Facter.
Add a new fact that determines the external IP and use this to restrict
access.
@GregSutcliffe could you take a look please?  You'll see the facts on the two new slaves only have RFC1918 addresses, which are being added to authorized_keys by the secure_ssh module.
=> Use external IP address fact for uploader SSH key access

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_plugin.sh
foreman_pipeline plugin requires Katello to run but our Jenkins is not prepared for it. When job on PR is triggered, Jenkins clones Foreman, then clones Foreman Pipeline and tries to build it. To force presence of Katello, Foreman Pipeline has it listed in dependencies to make sure it is available. Unfortunately, it is not possible to specify git source in gemspec, so Jenkins gets Katello from rubygems which causes gem clashes. This should introduce optional step into test_plugin_matrix job which clones Katello's repo
=> Adds Katello as optional step for plugin testing

puppet/modules/deploy/manifests/init.pp, puppet/modules/deploy/templates/auth_keys.erb, puppet/modules/freight/manifests/user.pp, puppet/modules/secure_ssh/templates/auth_keys.erb, puppet/modules/web/manifests/init.pp
Use either external_ip4 or IPv6 facts to permit access via SSH keys to
the web server etc, as most Rackspace hosts have v6 connectivity and
some AAAA records.
Should fix deploy_web and other web related things (package builds/pushes) since migrating to web02 and adding the AAAA record.
=> Permit IPv6 access via secure_ssh module

puppet/modules/slave/templates/test_pull_requests_bastion.json.erb, puppet/modules/slave/templates/test_pull_requests_foreman.json.erb, puppet/modules/slave/templates/test_pull_requests_foreman_bootdisk.json.erb, puppet/modules/slave/templates/test_pull_requests_foreman_discovery.json.erb, puppet/modules/slave/templates/test_pull_requests_foreman_docker.json.erb, puppet/modules/slave/templates/test_pull_requests_foreman_host_rundeck.json.erb, puppet/modules/slave/templates/test_pull_requests_foreman_openscap.json.erb, puppet/modules/slave/templates/test_pull_requests_foreman_packaging.json.erb, puppet/modules/slave/templates/test_pull_requests_foreman_pipeline.json.erb, puppet/modules/slave/templates/test_pull_requests_foreman_remote_execution.json.erb, puppet/modules/slave/templates/test_pull_requests_foreman_salt.json.erb, puppet/modules/slave/templates/test_pull_requests_foreman_setup.json.erb, puppet/modules/slave/templates/test_pull_requests_foreman_tasks.json.erb, puppet/modules/slave/templates/test_pull_requests_foreman_templates.json.erb, puppet/modules/slave/templates/test_pull_requests_hammer_cli.json.erb, puppet/modules/slave/templates/test_pull_requests_hammer_cli_foreman.json.erb, puppet/modules/slave/templates/test_pull_requests_hammer_cli_foreman_discovery.json.erb, puppet/modules/slave/templates/test_pull_requests_kafo.json.erb, puppet/modules/slave/templates/test_pull_requests_kafo_parsers.json.erb, puppet/modules/slave/templates/test_pull_requests_katello.json.erb, puppet/modules/slave/templates/test_pull_requests_katello_packaging.json.erb, puppet/modules/slave/templates/test_pull_requests_smart_proxy.json.erb, puppet/modules/slave/templates/test_pull_requests_smart_proxy_abrt.json.erb, puppet/modules/slave/templates/test_pull_requests_smart_proxy_discovery.json.erb, puppet/modules/slave/templates/test_pull_requests_smart_proxy_dynflow.json.erb, puppet/modules/slave/templates/test_pull_requests_smart_proxy_remote_execution_ssh.json.erb
As per -dev discussion, this should switch the Jenkins tests to manual-only. We can merge before Monday morn and revert after the bugday is done.
=> Switch to manual-only tests for forman bug day

.gitmodules, puppet/modules/foreman_debug_rsync/files/rsync_debug.te, puppet/modules/foreman_debug_rsync/manifests/config.pp, puppet/modules/freight/manifests/user.pp, puppet/modules/web/manifests/init.pp
Content stored in the web root should also be accessible via rsync, so
use a shared context.  Freight staing content should all be under the
public content context so it remains correct when copied to the web
roots.
---
This just implements the manually configured SELinux policy changes on web01 in Puppet.  Replaces @lzap's #142.
=> Manage SELinux configs for freight and rsync access

puppet/modules/foreman_debug_rsync/manifests/config.pp
It looks like puppet upstream module rsync moved to octal number as defaults
but this was merged into the tooling in 2010 and this was not backported to
stable distribution we use (RHEL7). For this reason, we must set this
explicitly.
Tested with foreman-debug, without this statement:
```
Apr 11 14:57:54 web02.rackspace.theforeman.org xinetd[24899]: START: rsync pid=7161 from=213.175.37.10
Apr 11 14:57:54 web02.rackspace.theforeman.org rsyncd[7161]: connect from nat-pool-brq-t.redhat.com (213.175.37.10)
Apr 11 14:57:54 web02.rackspace.theforeman.org rsyncd[7161]: rsync to debug-incoming/ from nat-pool-brq-t.redhat.com (213.175.3
Apr 11 14:57:54 web02.rackspace.theforeman.org rsyncd[7161]: Invalid "incoming chmod" directive: F644,D755
Apr 11 14:57:54 web02.rackspace.theforeman.org …
```
=> Make rsync permissions to work

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/plugins/foreman_discovery.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/plugins/foreman_pipeline.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/test_plugin.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/test_plugin_matrix.yaml
Allows plugins to specify, which databases to use for test_plugin_matrix. Current behaviour (testing against postgres, mysql and sqlite) is left as a default. The reason behind this is that foreman_pipeline needs Katello, but Katello does not officially support mysql. I have fixed a bunch of migration errors related to foreign keys that appear only on mysql, but I do not see how I could work around [Katello 's index being too long](https://github.com/Katello/katello/blob/master/db/migrate/20150613134559_add_rpm.rb#L20). It Requires Dynamic axis plugin for Jenkins.
=> Creates db axis dynamically for test_plugin_matrix

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/plugins/foreman_pipeline.yaml
I found out foreman_pipeline has [builds from other plugins](http://ci.theforeman.org/job/test_plugin_matrix/1445/) in the matrix. This was hopefully caused by specifying 'postgres' instead of 'postgresql' as one of the databases. ~~We should also be ok without defaults in test_plugin_matrix since they are supplied by test_plugin.~~
=> Change 'postgres' to 'postgresql'

puppet/modules/web/files/filter_apache_stats.sh, puppet/modules/web/manifests/init.pp
This automates something I've been doing manually for a while. Full parsing of the download metrics is CPU-intensive, so I don't want to load the server with that - instead I do some initial filtering server-side to reduce the amount of data to download, and then process that on my laptop. This is the server-side part, so I can just get the latest contents of `/var/cache/parsed_apache_logs` while updating my metrics.
This means we're truncating up to ~2-3Gb of raw logs to ~30-40Mb, which my monthly download allowance is very happy about. Stats for interest's sake:
```
[root@web02 ~]# du -sh /var/log/httpd/{yum_access.log-20160509,yum_access.log,deb_access.log-20160509,deb_access.log}
893M	/var/log/httpd/yum_access.log-20160509
381M	/var/log/httpd/yum_access.log
583M …
```
=> web: add daily download metrics filter script

.gitmodules, puppet/modules/freight/manifests/config.pp, puppet/modules/freight/manifests/init.pp, puppet/modules/freight/manifests/user.pp, puppet/modules/web/manifests/init.pp
HTTPS vhosts are all disabled by default via $https parameters, which
allows for bootstrapping when the certificate is not yet available.
On the first run, LE will run using webroot mode and will retrieve a
cert, authenticating using files served by the HTTP vhosts.  On
subsequent runs, $https can be enabled and the HTTPS vhosts will be
configured with the cert.  The letsencrypt module sets up a cronjob for
automatic renewals via the webroot.
A single certificate with SANs is used for all virtual hosts, which even
avoids the need for SNI.
Requires EL7, so post-[migration to web02.theforeman.org](https://groups.google.com/forum/#!topic/foreman-dev/8-HHA6uTGfs).
Once HTTPS is functioning then we can look at migrating all of the various pointers, e.g. documentation, redirecting HTTP …
=> Add LetsEncrypt to all web virtualhosts

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/deploy_web.sh
recent jekyll versions aren't tested with Ruby 2.0 anymore
=> use Ruby 2.3 to build the website

puppet/modules/slave/manifests/rvm_config.pp
on a new install:
```
Sep 10 09:25:26 banana puppet-agent[4010]: (/Stage[main]/Slave/Slave::Rvm_config[ruby-2.2]/Exec[ruby-2.2.3/update_rubygems]/returns) executed successfully
Sep 10 09:25:42 banana puppet-agent[4010]: (/Stage[main]/Slave/Slave::Rvm_config[ruby-2.1]/Exec[ruby-2.1.5/update_rubygems]/returns) executed successfully
Sep 10 09:25:57 banana puppet-agent[4010]: (/Stage[main]/Slave/Slave::Rvm_config[ruby-2.3]/Exec[ruby-2.3.0/update_rubygems]/returns) executed success
[...]
root@banana ~ # rvm 2.1.5 rubygems 2.4.6
Installed rubygems 2.4.8 is newer than 2.4.6 provided with installed ruby, skipping installation, use --force to force installation.
```
=> Update rubygems to match rvm default version

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_develop.sh
This allows two major benefits: shrinkwrap can be used to only pin
certain dependencies rather then entire trees, and download size is
greatly reduced as the module tree is flattened to reduce duplications.
=> Upgrade npm before npm install

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/test_proxy_develop.yaml
Seeing that puppet 2.6.0 was only being tested under ruby 1.8.7, I removed it from the matrix and the filter too.
=> Remove ruby 1.8.7 from smart-proxy test matrix

puppet/modules/slave/manifests/rvm_config.pp
As RVM with Ruby 2.3 is already bringing 2.5.1 by default, the current default leads to a change at every puppet run, as a downgrade 2.5.1 -> 2.4.8 is not done.
=> update rubygems version to 2.5.2

puppet/modules/slave/manifests/init.pp
on Ubuntu there was always a "firefox" package.
=> only use iceweasel on real Debian

puppet/modules/slave/manifests/init.pp
This updates ruby 2.x.x versions to current stable ones. This should also resolve https://bugs.ruby-lang.org/issues/11910 that is occurring in tests on ruby 2.3.0.
=> updated ruby 2.x.x versions to current stable ones

puppet/modules/debian/manifests/init.pp
otherwise the rake binstub in /usr/local/bin is not found on Debian 8 or newer
=> extend PATH for pbuilder

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/packaging_build_deb_coreproject.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/packaging_build_deb_dependency.yaml
As http://projects.theforeman.org/issues/15827 seems not to be solveable. Once this is merged, I'll open a PR to the docs and inform foreman-users.
=> disable armhf builds on Ubuntu/trusty

puppet/modules/debian/manifests/init.pp, puppet/modules/debian/manifests/pbuilder_setup.pp, puppet/modules/debian/templates/pbuilder_f70.erb
Ubuntu/xenial brings 4.2.6, which is new enough.
=> refs #17406 - add nodesource 4 apt repo

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_plugin.sh
Scan first thought the Gemfile in case the plugin gem is already
mentioned somewhere, as bundler doesn't like when something is mentioned twice.
Preparation for https://github.com/theforeman/foreman/pull/3670
=> Allow core dependency plugin testing

puppet/modules/slave/manifests/init.pp
Hopefully prevents emails like this:
```
/etc/cron.hourly/0yum-hourly.cron:
Repository 'isimluk-openscap' is missing name in configuration, using id
```
=> Add name param to yum repo to make yum-cron happy

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_develop.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_plugin.sh
Optional dependencies includes phantomjs for integration tests, which
is used for CI testing, but not for general production installation.
This reverts commit 0c1def1108574717f280621f6fbba7a7f1311065.
=> Revert "don't install optional npm dependencies"

.gitmodules, puppet/Rakefile, puppet/modules/quassel/manifests/init.pp, puppet/modules/users/manifests/account.pp, puppet/modules/users/manifests/slave.pp
I'd say let's try this... the sudo rules for users look good.
Diff of /etc/sudoers on a EL6 machine:
```diff
--- /etc/sudoers	2017-06-23 21:01:32.164000030 +0200
+++ /tmp/puppet-file20170623-11702-1amq4ie-0	2017-06-23 21:03:29.180000030 +0200
@@ -53,7 +53,13 @@
#
-## Defaults    requiretty
+Defaults    requiretty
+
+#
+# Refuse to run if unable to disable echo on the tty. This setting should also be
+# changed in order to be able to use sudo without a tty. See requiretty above.
+#
+Defaults   !visiblepw
#
@@ -74,8 +80,7 @@
#
-# Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin
-
+Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin
@@ -94,7 +99,7 @@
-%wheel	ALL=(ALL)	ALL
+# %wheel	ALL=(ALL)	ALL
@@ -106,4 +111,5 @@
+## Read drop-in files from /etc/sudoers.d (the # here does not …
```
=> use saz-sudo 3.0.9

puppet/modules/web/manifests/init.pp, puppet/modules/web/manifests/jenkins.pp, puppet/modules/web/manifests/letsencrypt.pp, puppet/modules/web/templates/jenkins.conf.erb
=> Allow running Jenkins over HTTPS

puppet/modules/web/manifests/jenkins.pp
Since it's set to root:root 750 by default this allows access to the .well-known directory which makes letsencrypt work.
=> Set the docroot owner for the jenkins vhost

puppet/modules/web/files/filter_apache_stats.sh
This prevents cron mails from being sent every day.
While here, fix some shellcheck warnings.
=> remove echo from filter_apache_stats

puppet/modules/web/manifests/init.pp
This results in a duplicate resource and I don't exactly know why yet.
Revert it for now.
=> Revert web::base for duplicate apache resource

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_develop.sh
Adding this check ensures that the RPM build step that has caused
failing builds multiple times is tested before code goes into the
repository.
=> Add webpack build step to test_develop

puppet/modules/redmine/manifests/init.pp, puppet/modules/redmine/templates/postgresql_backup.sh, puppet/modules/redmine/templates/postgresql_backup.sh.erb
This was still dumping the database to the old location. It also adds the .erb extension and introduces the DBNAME variable
=> Fix redmine backup script

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/plugin_pr_checkout.sh
`popd <dir>` is not a thing [1] and produces errors on modern bash
(tested on 4.3 and 4.4):
popd fff
bash: popd: fff: invalid argument
popd: usage: popd [-n] [+N | -N]
and even on older (4.2) bash, this would not produce what we expect:
bash-4.2.46-29.el7_4.x86_64
/tmp
/tmp/foo /tmp
/tmp/foo
/tmp/foo
/tmp/foo
[1] https://www.gnu.org/software/bash/manual/html_node/Directory-Stack-Builtins.html
=> use `popd` instead of `popd <dir>`

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/deploy_katello_site.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/deploy_web.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/gemset_cleanup.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/pkg_generate_source.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/proxy.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_develop.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_hammer_cli_foreman.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_katello.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_plugin.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_upgrade.sh
Per a conversation on IRC with @timogoebel this would hide the overly verbose RVM output.
=> Hide verbose rvm output in jobs

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_develop.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_katello.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_plugin.sh
It turns out that this is broken and likely has been broken for a long time.
=> Refs #21431 - Run seeding as a separate command

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release_push_rpm.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release_test.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/systest_foreman_puppet_pc1.yaml
In release_test.yaml it was already a dummy since the combination filter no longer allowed it. In the others I think it's no longer needed.
=> Remove f24 builds

puppet/modules/users/manifests/account.pp
We don't actually have a way to remove old keys (although we can stop deploying them by settting ensure to something else, it's a pain to remove them by hand).
=> Enable cleanup of old user accounts

puppet/modules/users/manifests/account.pp
This reverts commit 7c4e69995f9207916d25109e79a3fd82d88cabcd.
The previous code had managehome => true so the homedir is already
cleaned up.
=> Revert "Enable cleanup of old user accounts"

puppet/modules/slave/manifests/init.pp
In order to use chrome headless with Selenium, and get rid of phantomjs.
For the moment, both can be installed to test https://github.com/theforeman/foreman/pull/4987
When that PR is merged and we no longer need phantomjs and firefox, 
we can remove them on another PR.
=> Install google-chrome in slaves

puppet/modules/freight/files/deb-HEADER.html
all other releases have way too outdated foreman releases
also replace `rc` with `<version>` because we don't really have an rc pocket
=> only list jessie, stretch, trusty and xenial

puppet/modules/slave/manifests/init.pp
Currently fails with:
Failed to apply catalog: Parameter baseurl failed on Yumrepo[google-chrome]: Validate method failed for class baseurl: bad URI(is not URI?): http://dl.google.com/linux/chrome/rpm/stable/\$basearch at /etc/puppetlabs/code/environments/production/modules/slave/manifests/init.pp:237
Also fixes a puppet-lint check that ensure should be first.
=> Fix google-chrome yumrepo

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/packaging_build_rpm.sh
There were 3 solutions I could think of:
Preventing the run in the first place by changing packaging_test_pull_request would be nice, but that job is not managed by JJB so was IMHO somewhat risky. It'd save more resources but this job fails very fast so should be light enough.
This made the most sense since it produces an understandable and short error message if it's somehow misconfigured. We can later always exit 1 when all known releasers are in all supported branches.
We could also add the releasers to the 1.15 and 1.16 branches.
In the end we might up using all 3.
=> Handle unknown releasers in packaging_build_rpm.sh

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_katello.sh
Rails 5 does not handle dropping a non-existent database gracefully
=> Drop db:drop from Katello develop PR test

.gitmodules, puppet/modules/web/manifests/htpasswd.pp
The httpauth module uses the webrick gem and that's nasty. Looks like
it's breaking web02 right now so it's replaced with a much simpler
module using simple puppet types and functions
=> Replace httpauth with htpasswd module

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_develop.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_plugin.sh
Since 1696b3087 in foreman-packaging npm 5.x is used for DEB builds and it's working fine.
=> use npm 5.x

puppet/modules/freight/manifests/user.pp
the vhost options are ignored if we define `directories` [1]
[1] https://github.com/puppetlabs/puppetlabs-apache#options-1
=> set options inside the directory config

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/proxy.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_develop.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_foreman_virt_who_configure.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_hammer_cli_foreman.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_katello.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_plugin.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_upgrade.sh
I'm getting some unexpected aborts on rake test command in remote
execution. I don't see reason hiding the trace when the rake calls in
our CI fail on exception. I believe this can help not just me but all
the future generations trying to figure out WTH it going on.
=> Add --trace to rake tasks

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_katello.sh
3cfb9889a769d6cfb872bc4b6d7aaaf4406d8951 removed db:drop alltogether,
which means we can end up running on a DB that had migrations from
another branch applied, which is no good.
try to drop the DB, but ignore all errors, thanks Rails 5
=> try hard to drop the db in the katello tests

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_plugin.sh
The way this works currently, db:drop db:create db:migrate runs prior to
running the tests. This works, because when these 3 tasks are called by
rake, there is no environment, so the migrations cannot assume any
schema.
However, after the tests run, there's already an existing schema. When
we call db:drop, db:create db:migrate all 3 on the same rake command, by
the time we get to 'db:migrate' - the application has already loaded the
schema we had prior to db:drop, instead of an empty one.
This means, a call like "Host.unscoped.all" is translated to
"SELECT \"hosts\".* FROM \"hosts\" WHERE \"hosts\".\"type\" IN
('Host::Managed')""
when it should be:
"SELECT \"hosts\".* FROM \"hosts\"
This affects an early migration
20090916053824_change_host_build_default_to_false.rb, at that date,
there …
=> Drop & migrate on separate rake commands

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release_test.yaml
Repoclosure has 'develop' as a default branch which gets used because release_test does not pass it in predefined parameters.
=> Specify branch for repoclosure

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/packaging_repoclosure.sh
tfm-ror51 is not used when testing [repoclosure](http://ci.theforeman.org/job/packaging_repoclosure/37707/console).
=> Use tfm-ror51 in repoclosure

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/systest_foreman.sh
The pc1 repo for stretch is now [available](https://tickets.puppetlabs.com/browse/PA-515?focusedCommentId=482629&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-482629), so we can use it in systest. I hope the missing [dependency errors](http://ci.theforeman.org/job/systest_foreman/14210/console) will disappear as stretch will have the puppet available.
=> Allow pc1 repo for stretch

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/systest_foreman.sh
Needs a change in [bats](https://github.com/theforeman/foreman-bats/pull/119) to work.
=> Add custom url for plugins in systest

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/foremanPluginsRelease.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/foremanRelease.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/katelloRelease.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release/foreman-nightly-release.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release/foreman-plugins-release.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release/katello-nightly-release.yaml
The cron trigger from the pipeline itself seemed to partially or never truly work. This reverts back to normal cron trigger on the job definition itself.
This also updates a bug in the plugins release pipeline where it never actually called `push_rpms` (oops). This also make a strategic change to do repoclosure + push per release stream. This prevents broken release streams from blocking others. i.e. in progress 1.17 doesn't block nightly.
=> Fix release cron and pipeline job

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/systest_foreman.sh
el7 tests failing on DNS resolution for host, this should help. Needs a change in [bats](https://github.com/theforeman/foreman-bats/pull/120)
=> Skip system checks for systest

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/kafo.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/test_kafo_master.yaml
While it may work on Ruby 1.x and old Puppet version, we no longer really care about it. This allows us to simplify the test matrix.
=> Update the kafo test matrix

puppet/modules/jenkins_job_builder/files/theforeman.org/generate_jobs.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/foreman.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/rvm.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/test/testKatello.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/tests/katello-pr-test.yaml
This is an attempt at re-writing test-katello as a pipeline using parallelism. The job can be browsed at [1]. This still needs the JS tests added to it. I wanted to open this up to get some thought around this approach as compared to a more linear approach. @mmoll @egolov  If you wouldn't mind lending some thoughts.
[1] http://ci.theforeman.org/blue/organizations/jenkins/test-katello/activity
=> Add pipeline based Jenkins job for Katello PRs

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/packaging_trigger_installer_develop.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/test_develop.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/test_proxy_develop.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/publishers/release_nightly_build_foreman_deb.yaml
@ekohl Thanks for the heads up. I split deb and rpm here to be explicit.
=> Split release_nightly_build foreman into rpm and deb

puppet/modules/slave/manifests/init.pp
bf12835d0b08cad823eaf26f0a2e6ad0c8045589 removed the template without removing the actual config. This ensures the config is actually purged.
=> Purge old katello PR hook

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/scm/foreman-packaging.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/scm/foreman.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/scm/kafo.yaml
By setting this refspec we only retrieve the PR that we need to build
rather than every single PR. This saves a bandwidth, IO and thus time,
especially as the repository gets older.
=> Only retrieve the relevant PR with GHPRB

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/obal.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/rpm_packaging.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/triggers/github_pr.yaml
My understanding is that with declarative pipelines, this style is more the norm and can avoid this error:
```
WorkflowScript: 39: Expected a step @ line 39, column 21.
action = "scratch"
```
Which happens if a closure is not wrapped in a `script {}` which is kinda ugly to double wrap.
=> Switch obal function to named parameters

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/tests/katello-pr-test.yaml
7d96a8bd3d2896d78c1acc9ffb031bf21c42979c started to use the git lib so it must be included.
=> Include git in the katello-pr-test

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/gemset_cleanup.sh
This is not available in every job and can sometimes fail the build
while new builds already run db:drop at the start.
=> Ignore db:drop failures in gemset_cleanup

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/git.groovy
Attempting to fix (http://ci.theforeman.org/job/katello-pr-test/746/console) the test case we ran worked but was only a single data point.
=> Use sha1 for pull request builder

puppet/modules/slave/manifests/vagrant.pp
The plugin is installed as the user jenkins and /root is not readable.
=> Download vagrant openstack gemfile to a readable location

puppet/modules/slave/manifests/vagrant.pp
When upgrading from 1.4.2 to 2.0.2 vagrant wants to upgrade some
internal data. This shows an interactive prompt which needs a TTY. We
don't care about our boxes so it's easier to just remove the directory.
We only do this if we see the old rackspace dummy box to make it
idempotent.
=> Wipe out old vagrant dirs

puppet/modules/slave/manifests/vagrant.pp
All nodes have been migrated so this cleanup code is no longer needed.
=> Remove temporary vagrant cleanup code

puppet/modules/slave/manifests/vagrant.pp
This gem contains a commit to rip out the version check which breaks vagrant ssh-config (and is undesired in general).
=> Update vagrant-openstack-provider to a new version

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/systest_foreman.sh
The debug info contains API auth tokens so this is a major security
issue.
=> Do no not run vagrant up with --debug

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/git.groovy
This will fetch both the PR ref and the base branch ref (i.e. master).
I'm hoping this will produce the following (e.g.) fetch:
```sh
git fetch --tags --progress https://github.com/Katello/katello '+refs/heads/master:refs/remotes/origin/master' '+refs/pull/7197/*:refs/remotes/origin/pr/7197/*'
```
Relevant docs https://github.com/jenkinsci/ghprb-plugin#creating-a-job
=> Update the refspec to include the base branch

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/systest_foreman.sh
Synced folders break because they attempt to use NFS and we don't need
them anyway, just causing a slowdown. There Debian image is also cripled
so we need another workaround there.
=> Implement workarounds for systest

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/systest_foreman.yaml
This is no longer used and we always run puppet tests.
=> Remove unused run_puppet_tests option

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/publishers/systest_foreman.yaml
Forklift outputs test.tap files. This change ensures Jenkins can find
the correct results.
=> Fix systest bats reporting

puppet/modules/slave/templates/Vagrantfile.erb
In various jobs I've seen that it can take longer than the default 200
seconds for a server to come up. Hopefully these values are a bit safer.
=> Increase rackspace timeouts

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/packaging_test_pull_request.yaml
Should add `--test` to scratch builds so that tito does not complain about missing tags when testing PRs
=> Use gitrelease on rpm scratch builds

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release_packages.yaml
Since we block on debs, maybe we should have the same for rpms.
=> Block release_packages on building rpms

puppet/modules/slave/manifests/packaging/rpm.pp
5f4579b29e5e76a34140e70dff2294cad71873d1 split copr config into a separate file but that took the copr variables out of scope.
=> Fix scoping on copr template

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/rpm_packaging.groovy
we have slaves that have an old git client, which does not support the
inverted, lowercase, filters
=> use a positive --git-filter

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/foremanRelease.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/katelloRelease.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/foreman-discovery-image-publish.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/systest_foreman.yaml
Because we provision on Rackspace (which has IPv6) and the vagrant-openstack-plugin can't decide which IP it should use, we pin to nodes with IPv6.
=> Limit vagrant jobs to hosts with ipv6

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_plugin.sh
Currently the plugins with webpack assets, are not getting their
dependencies fulfilled and webpack always fails to compile in the
test_plugin_pull_request job. The reason is that `npm install` is ran
**before** putting the plugin in the gemfile.
This change runs `npm install` a second time after the Gemfile has been
updated to ensure we have the npm dependencies ready for webpack.
https://github.com/theforeman/foreman_remote_execution/pull/130 for example benefited from this change (I changed it manually on Jenkins)
=> Install npm for plugins in test job

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_develop.sh
we already have tests for the seeds in core, no need to rerun the seeds. This was added mostly to make sure plugin seeds run properly.
=> Drop db:seed run from develop tests

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_plugin.sh
Trying to run `npm install` after `npm install npm` works.
However, the 2nd time it runs, to install the plugin npm dependencies,
it fails.
The reason is that 'node_modules/.bin/npm install' can only
run once. After it runs, since 'npm' is not a dependency of Foreman in
package.json, it will just erase it.
To fix this, I am just installing npm once and then calling
`node_modules/.bin/npm install` *after* the Gemfile contains the
plugin. This ensures we install both Foreman npm deps and plugin's deps.
Example of broken tests because of this:
- http://ci.theforeman.org/job/test_plugin_matrix/5164/database=postgresql,ruby=2.4,slave=fast/consoleFull
- http://ci.theforeman.org/job/test_plugin_matrix/5147/database=postgresql,ruby=2.3,slave=fast/console
Example of :+1:  tests after the fix is …
=> Install npm assets just once

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/test/testKatello.groovy
should work around the issue of `/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler (LoadError)`  during an npm install
=> Bundle exec npm install within foreman

puppet/modules/slave/templates/test_pull_requests_foreman_bootdisk.json.erb, puppet/modules/slave/templates/test_pull_requests_foreman_digitalocean.json.erb, puppet/modules/slave/templates/test_pull_requests_foreman_discovery.json.erb, puppet/modules/slave/templates/test_pull_requests_foreman_expire_hosts.json.erb, puppet/modules/slave/templates/test_pull_requests_foreman_host_extra_validator.json.erb, puppet/modules/slave/templates/test_pull_requests_foreman_monitoring.json.erb, puppet/modules/slave/templates/test_pull_requests_foreman_omaha.json.erb, puppet/modules/slave/templates/test_pull_requests_foreman_userdata.json.erb
This should disable the `Waiting for stable build of` message, see https://github.com/openshift/test-pull-requests/blob/699cc3085e3a1cd090d9c185781bf676ab183191/test_pull_requests#L2253 for reference.
cc: @lzap, @ehelms
=> do not require downstream stability

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/foreman-hammer-nightly-systest.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/foreman-mysql-nightly-systest.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/foreman-puppet-nightly-systest.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/foreman-puppet-pc1-systest.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/foreman-umask-077-systest.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release_nightly_test_deb.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release_test.yaml
systest jobs were complaining about an unreachable host and bombing out.
i think i've figured out that `node: 'el && ipv6'` only works for non-matrix jobs.
=> fix labels for systest family jobs

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/test_katello_rubocop.yml
[test_katello_rubocop_temp](http://ci.theforeman.org/job/test_katello_rubocop_temp) will need to be deleted after this is merged.
=> test_katello_rubocop - remove _temp suffix

puppet/modules/jenkins_job_builder/files/centos.org/pipelines/test/containers.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/git.groovy
newer versions of the git plugin do not like that. not setting it does
the right thing: uses the default
=> don't set mergeStrategy: default

puppet/modules/web/templates/web.conf.erb
As per https://community.theforeman.org/t/moving-event-data-to-discourse/8971/3 this redirects the calendar and ICS file to the equivalents on Discourse.
=> Add events redirect for calendar and ICS file

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/plugins/bastion.yaml
discovered when helping @beav with Katello/bastion#227.
=> test_bastion_assets_precompile was timing out way too quickly

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/build/build_rpm_rubygem_katello_nightly.yaml
double check that [build_rpm_rubygem-hammer_cli_katello_nightly](http://ci.theforeman.org/job/build_rpm_rubygem-hammer_cli_katello_nightly) is gone after this is merged.
=> remove build_rpm_rubygem-hammer_cli_katello_nightly job

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/tarballsRelease.groovy
Should fix [tarballs-release](http://ci.theforeman.org/blue/organizations/jenkins/tarballs-release/detail/tarballs-release/1/pipeline)
=> Escape $ in tarballsRelease.groovy

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/tarballsRelease.groovy
Pipeline does not expect declared variables, so I replaced them with [environment directive](https://jenkins.io/doc/book/pipeline/syntax/#environment)
=> Fix pipeline syntax

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/rvm.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/tarballsRelease.groovy
I changed the base_dir so that the tarballs are uploaded to proper directory and not all to 'foreman'.
Each project name is now added to a gemset name, so that parallel branches do not clash with each other.
=> Fix upload folders, create separate gemsets

puppet/modules/jenkins_job_builder/files/theforeman.org/unmanaged_jobs.rb
the machine where jenkins currently lives is using ruby 2.0. the
safe navigation operator wasn't introduced until ruby 2.3.
=> don't use ruby's safe navigation operator

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/tarballsRelease.groovy
This ensures we have no files like Gemfile.lock left behind from any previous run.
=> Clean the workspace when releasing tarballs

puppet/modules/jenkins_job_builder/files/theforeman.org/unmanaged_jobs.rb, puppet/modules/jenkins_job_builder/manifests/config.pp
This still doesn't make it idempotent, but it shouldn't bork when
unmanaged_jobs.rb returns an empty string because there are no unmanaged
jobs.
Note this is untested and there's probably a much cleaner way to do this.
=> Handle the case where there are no unmanaged jobs

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/packaging_build_rpm.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/packaging_test_pull_request_rpm.sh
This script is only used on rpm/1.16 and rpm/1.17 so we can drop the rpm/develop specific code. They also don't have a packages directory so that can be dropped too.
=> Clean up legacy RPM package testing

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/tarballsRelease.groovy
The clearWorkspace didn't work. This uses the CleanCheckout extension
which does appear to work.
We also match the exact git URLs for consistency.
=> Use the correct cleanup method in tarballsRelease

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/tarballsRelease.groovy
The `release_packages` task always fails because manual steps are needed to proceed - signatures must be uploaded and foreman-packaging updated.
=> Remove post action for tarballs-release

puppet/modules/redmine/manifests/init.pp
This is untested. Probably best to roll it out with noop to see the diff before applying it.
=> Run Redmine on HTTPS only with a redirect

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/builders/foreman-discovery-image-publish.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/foreman-discovery-image-publish.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/scm/foreman-discovery-image.yml
also:
- consolidating SCM and builder modules since nothing else uses them
=> fix typos in foreman-discovery-image-publish's SCM module

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/katelloRelease.groovy
This ensures it runs correctly on a node with IPv6 which we need for
forklift.
=> Bind the katello test step to ipv6

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_develop.sh
When the database doesn't exist, the rake task will fail. Because that
means we've reached the desired state, this is actually not a problem
for us.
cc @tbrisker
=> Allow db:drop to fail

puppet/modules/scaleway/files/manage_snapshots.rb, puppet/modules/scaleway/manifests/cron.pp, puppet/modules/scaleway/manifests/init.pp
This deploys a cron script for creating snapshots over the Scaleway API. It's currently hardcoded to the AMS zone, where Discourse runs - we can expand the module to handle the Paris zone and snapshot Redmine once it's all working. It's quite verbose at the moment, we can tune that. Here's some sample output:
```
$ ruby ./manage_snapshots.rb
Scaleway Snapshot Management for discourse01.theforeman.org
Creating snapshot of 6f27df04-c0bf-4ded-bfa5-7626f40720d5
49dc1034-671f-43df-b98b-fb957f8c4827 in progress
// sits in 1 min loops for ~10-15 min
49dc1034-671f-43df-b98b-fb957f8c4827 created
Cleaning up snapshots on 6f27df04-c0bf-4ded-bfa5-7626f40720d5 - keeping 3
DELETE d2bb6d23-3865-4857-8f26-33e643689078: 204
// 204 is the correct return code for a successful delete
```
=> Scaleway snapshot management

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release_packages.yaml
This breaks the 1.17 release but it's hard to support both. With 1.19 being branched we are more likely to use this style than the old one.
=> Update release_packages job for 1.18+ style

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/test/testKatello.groovy
This adds eslint testing to katello PRs, currently this does
not exist.
=> Add eslint task to katello pipeline

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/builders/systest.yaml
Otherwise you'd get
```
[WARNING]: could not parse environment value, skipping: [u'{{ bats_environment
}}']
```
=> Correctly pass in the FOREMAN_EXPECTED_VERSION

puppet/modules/redmine/files/git_repos.sh
script/rails was changed to bin/rails in the new rails version we're
using for Redmine. This also adds some error handling so you can't
accidentally run it incorrectly.
=> Handle redmine update in repo updates

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release_test.yaml
We've always tested releases with PostgreSQL but in c57d43f0af47cecc867bf6d65b1ce8ae8c82cb6c this was changed to MySQL.  Probably unintentional.
=> Test releases on PostgreSQL

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/test/rpm_packaging.groovy
Find the spec file explicitly rather than relying on wildcard paths
that don't work for all packaging release workflows.
=> Allow version and release check to work more broadly

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/katelloInstallerNightlyRelease.groovy
https://github.com/theforeman/foreman-packaging/commit/b98dbee1c4b5fc5f575db0dd6c401a0bbb00fdc7 renamed the directory to match the package name. This reflects that change.
=> Correct katello-installer nightly builds

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/koji.groovy
the package name is already in the "context" and this makes the description better readable
requested by @ekohl in #762
=> only list the koji task id in the description

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/test/testKatello.groovy
We added this workaround due to '.eslintrc' being
"up the tree" for angular tests run in  engines/
bastion_katello. The root .eslintrc is for
React code. A Katello PR will move the .eslintrc
file to webpack/ so its no longer "up in the tree"
and picked up by running eslint in engines/ directory
=> Removes workaround for eslint in katello

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/builders/systest.yaml
Depends on https://github.com/theforeman/forklift/pull/824
=> Apply the rackspace hostname workaround on systests

puppet/modules/jenkins_job_builder/files/centos.org/ansible/provision.yml
the "all" group is created automatically by ansible [1]
and writing it seems to sometimes confuse the task:
fatal: [localhost]: FAILED! => {"changed": false, "msg": "could not write content temp file: <built-in function all> is not JSON serializable"}
[1] https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html
=> don't explicitly mention the all group

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/duffy.groovy
sometimes jobs fail because the cico data we got is incomplete/empty, this makes it easier to spot such failures
example failure, where it *seems* we got an empty response: https://ci.centos.org/job/foreman-katello-nightly-test/76/
=> archive ci.centos.org data for easier job failure analysis

puppet/modules/jenkins_job_builder/files/centos.org/ansible/provision.yml
sometimes, cico returns
{"message": "Requested servers successfully", "hosts": {}, "ssid": "012345679"}
with the hosts list being empty. This makes the data useless for further
processing. Try to get a list of hosts from cico again and if that
returns no hosts too, properly fail inside the playbook, instead of
writing an empty inventory and then failing in the next steps of the
pipeline.
=> try harder to get a node from cico and fail properly

puppet/modules/debian/manifests/pbuilder_setup.pp
The subdirectories of result might not exist. This causes an error when cleaning. The mindepth ensures the directory itself isn't removed.
=> Fix pbuilder cleaning

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/builders/systest.yaml
Rackspace reports the issue should be solved with the newest version of nova-agent and the workaround is no longer needed.
This reverts commit 4ac6f4c69b727154049e110bcadf2056e45b12c0.
=> Revert "Apply the rackspace hostname workaround on systests"

puppet/modules/web/manifests/init.pp
There is no copy for 1.20 yet, so I've left `latest` and `next` as is.
=> Update `stable` manual version to `1.19`

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/obal.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/foremanClientRelease.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/foreman_packaging_release.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/rubygemRPMNightlyRelease.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/tfmROR52.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/test/tfmROR51.groovy
The git checkouts on each call to obal() will fail if within a
parallel block. Let's make this explicit until we switch to the
Obal package.
=> Call setup_obal explicitly

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/obal.groovy
In a parallel run, these variables can end up evaluating to the last
value passed in.
=> Ensure variables are scoped to instance of obal method

puppet/modules/web/templates/yum.conf.erb
This will allow whatever is copied from koji to be used directly
instead of providing this rewrite that can add confusion.
=> Drop Fedora rewrite rule fc ->

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/katelloInstallerNightlyRelease.groovy
It outputs a lot of warnings that running with ruby 2.2 is deprecated.
=> Run katello-installer-release-master with ruby 2.4

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/builders/systest.yaml
Otherwise 1.20 ends up as a float 1.2.
https://ci.theforeman.org/job/release_test/250/
=> Quote versions in YAML

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/duffy.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/foreman_infra.groovy
To fix nightly and prevent jobs on the ci.theforeman.org side form having to include all of `duffy.groovy` into their pipeline when its all unused on that side.
=> Move build_job_description to foreman_infra.groovy

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/test_kafo_pull_request.yaml
Hopefully this fixes the errors from https://ci.theforeman.org/job/test_kafo_master_pull_request/404/puppet=4.10,ruby=2.0/console
To install do: 'rvm install "ruby-2.0.0-p648"'
=> Set Kafo RVM version to 2.0.0

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release_nightly_test_deb.yaml
Currently nova provisioning is broken on rackspace for Ubuntu. It doesn't set the fqdn correctly which makes the installer fail. This means we haven't had nightlies for a long time. While this isn't pretty, it's better than having no nightlies at all.
=> Skip Ubuntu tests in release_nightly_test_deb

puppet/modules/jenkins_job_builder/files/centos.org/pipelines/lib/foremanCentosJob.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/ansible.groovy
Tested and worked as a solution to limit to ci.centos use. There really isn't any sensitive information to worry about but I can update to the same pattern there if you want.
=> Use extra vars from command line for centos jobs

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/rvm.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/deploy_web.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/pkg_generate_source.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/kafo.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/proxy.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_bastion_assets_precompile.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_develop.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_hammer_cli.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_hammer_cli_foreman.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_hammer_cli_foreman_discovery.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_hammer_cli_foreman_pull_request.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_hammer_cli_pull_request.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_kafo_parsers_master.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_katello.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_plugin.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_proxy_develop_pr_core.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_proxy_develop_pr_rubocop.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_upgrade.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/builders/foreman-plugins-pull-request.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/builders/smart-proxy-plugin.yaml
Bundler 2.0 requires ruby 2.3 and rubygems 3.0 or later, breaking all of
our pipelines. This is a temporary pin to get CI working again until we
figure out which pipelines can be upgraded to the newer version and
which cannot.
Fixes #894
=> Pin bundler to < 2.0

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/foreman.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/test/testKatello.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_bastion_assets_precompile.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_develop.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_katello.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_plugin.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_upgrade.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/builders/foreman-plugins-pull-request.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/builders/systest.yaml
Organizations an Locations are now always enabled, no need to manually
enable them in the ci pipelines.
=> Remove organization/location enabling in CI

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/foreman_infra.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/foremanRelease.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/katello/nightly.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/test/ci_centos_integration_test.groovy
when a pipeline runs multiple steps in parallel on the same node, each
step gets an unique workspace (jobname@XXX for all but the first run).
this means that when we write the remote job details to the workspace,
we might not overwrite any pre-existing files in there.
this leads to jobs with multiple links like seen in [1], which is
confusing.
let's be more explicit and only add one link at at time to the
description.
[1] https://ci.theforeman.org/job/katello-nightly-rpm-pipeline/659/
=> only add job link for the currently running job

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/rubygemRPMNightlyRelease.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/hammer-cli-katello-master-release.yaml
While it has disableConcurrentBuilds, it doesn't appear to actually apply this because we still see concurrent jobs. Though not 100%:
=> Disable concurrent hammer builds

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/rpm_packaging.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/test/rpm_packaging.groovy
* introduce more wrappers for git diff and finding of changed files
* use git diff instead of find to find the old and new specfiles
using find might find the wrong spec file as we sometimes have multiple packages with the same spec name
* move old vs new path check to the begining of the test
=>  use git diff instead of find to find the old and new specfiles

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/rpm_packaging.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/test/rpm_packaging.groovy
the old logic would also find the newly added path, but we actually only
need to look for "deleted" or "changed" files, the "added" ones can
never be "old_path"
=> fix the selection of "old path"

puppet/modules/web/manifests/init.pp
Before this change, we would set Cache-Control for *ALL* of
downloads.theforeman.org, leading to the CDN caching directory indexes
which is confusing during release time when you push new files but don't
see them.
Intead, let's just set Cache-Control on the actual files we want to
serve from the CDN for a long time.
=> only set a long cache time for files, not indexes

puppet/modules/web/manifests/init.pp
this was enabled before, so let's not lose it
=> add back MultiViews to downloads.tfm.o

puppet/modules/freight/manifests/user.pp
freight uses a .refs folder underneath `dists/<name>-<time>/` to keep
track of "still referenced" debs for housekeeping of `pool/`.
As the timestamp changes every time freight runs, simple mirroring tools
(like wget or rsync) will think these files are new and re-download them
every time, producing more traffic than needed.
These files are internal to freight and not used or referenced in the
repository metadata, so no real Debian client will ever try to access
them. Thus we can just safely exlude them from being transferred save a
lot of traffic.
This commit should save us about $600-700 of traffic each month.
=> don't serve freight's .refs folder via http and rsync

puppet/modules/freight/files/stagingdeb-HEADER.html
stagingdeb points to Fastly and that does not offer rsync
=> poin to rsync.tfm.o not to stagingdeb.tfm.o in rsync url

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/pipeline/foreman-nightly-rpm-pipeline.yaml
We added this dependency when the installer was split over 2 repositories. This was intended to keep them closer in sync.
Now that it's only in the foreman repository, this isn't really needed anymore.
The effect is that it really does become a nightly again, which will reduce the spam on Discourse. That was increased because we built an installer for every merge to foreman-packaging.
=> Remove the reverse dependency on the installer

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/tests/foreman-develop-test.yaml
Previously we had a 45 minute quiet period. This ensured we didn't queue up too many nightly builds, for exampe when someone was merging multiple changes.
It also sets the github properties so you get the proper Github links.
=> Reintroduce the quiet period on foreman-develop-test

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/foreman-x-develop-release.groovy
Deb releases sometimes take more than 2 hours, causing the pipeline to
timeout.
=> Modify foreman develop release timeout

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release_nightly_build_deb.yaml
This is an alternative to GH-961, dropping arm completely from nightlies.
=> Drop arm builds from nightlies

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/test/test_foreman.groovy
The job `foreman-develop-release` also triggers `release_nightly_build_deb`. This causes duplicate builds and greatly increases the load on our infra.
=> Don't trigger release_nightly_build_deb in test_develop

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/test/test_foreman.groovy
Otherwise, Rake::TestTask thinks that e.g. '2.5' is the ruby binary it
should use to run tests - https://github.com/ruby/rake/blob/master/lib/rake/file_utils.rb#L10
=> Rename RUBY env var to RUBY_VER

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/foremanPluginsRelease.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/foremanRelease.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/katello/3.10.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/katello/3.9.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/katello/nightly.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/packaging_repoclosure.sh
The scl-sclo repository was removed in 1.20.
=> Remove scl-sclo in repoclosure checks

puppet/modules/jenkins_job_builder/manifests/config.pp
Sometimes this job hangs and needs to be killed or it'll run forever. Because it first takes a lock, this then blocks other jobs from updating.
=> Add a timeout to JJB cronjobs

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/release.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/foreman-deb.groovy
* Push using the correct credentials
* Perform cleanup in the correct jobs. These run on different nodes so they should happen inside each stage. Deb pushing doesn't generate any files so no cleanup is needed.
=> Fix Debian pipeline

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_upgrade.sh
In the past we've seen that db:drop and db:create need to be separate commands because of caches that aren't flushed.
=> Split db:drop into a separate commands

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/foreman-x-develop-release.groovy
This method is not allowed in a sandbox and breaks our release pipelines.
=> Do not use isAllWhitespace

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release_packages.yaml
foreman-release should only be released for RPMs on 1.20+.
This is untested so I'd appreciate a careful review.
=> Add foreman-release to release_packages

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/test/foreman-installer-develop-test.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/test/foreman-selinux-develop-test.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/vars/hammer-cli-katello-master-release.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/vars/hammer-cli-katello-master-test.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release/foreman-installer-develop-release.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release/foreman-selinux-develop-release.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release/hammer-cli-katello-master-release.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/tests/foreman-installer-develop-test.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/tests/foreman-selinux-develop-test.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/tests/hammer-cli-katello-master-test.yaml
Individual commits have relevant commit messages:
d741fbd6 (Ewoud Kohl van Wijngaarden, 3 minutes ago)
Introduce a hammer-cli-katello-master-test job
This runs the tests before releasing.
d6b1d286 (Ewoud Kohl van Wijngaarden, 20 minutes ago)
Introduce a foreman-selinux-develop-test job
This follows the pattern of having a -test job to verify functionality and a -release job to build packages.
It avoids the rebuild for every foreman-packaging change issue.
This change drops the timed builds which aren't needed for foreman-selinux since it doesn't bundle anything.
673b7205 (Ewoud Kohl van Wijngaarden, 35 minutes ago)
Add a foreman-installer-develop-test job
This works towards the pattern of having a -test job to run tests and then a -release job to actually release it.
An additional benefit …
=> Update release jobs

puppet/modules/slave/manifests/init.pp
5c1ba8ac124b120492c4d91ba2455f6da195ac90 introduced a foreman-selinux test job, but this requires selinux-policy-devel to be installed.
=> Ensure selinux-policy-devel is installed

puppet/modules/jenkins_job_builder/manifests/config.pp, puppet/modules/jenkins_job_builder/manifests/init.pp
The timeout was redundant since it matched the default config value. Run is unused since 3826ee4d844d46e8800d638117b5e193463d2ba2.
=> Modernize the JJB module

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/deploy_yum.yaml
66c997a0c5314f6309a864437c8c3de5daedda30 started to use the library function but didn't include it.
=> Include the release lib for deploy_yum

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/builders/foreman-plugins-pull-request.yaml
Salt depends on foreman-tasks which needs npm install to properly
compile webpack, but because salt doesn't have a package.json npm
install is run too early, when only foreman core is set up.
=> Always install node modules for plugin prs

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/nightly_packaging.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/source/foreman.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release/package/foreman-develop-package-release.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release/source/foreman-develop-source-release.yaml
This changes the idea of a 'test' job that is run on PR merge to
a source release job. The source release job aims to test the code
and then create a source release if that tested code is green.
The previous release job is renamed to be a package-release job to
better specify that its focused only on releasing a package.
The overall idea is to split source generation and release from
package creation given that source can be an input to multiple places.
=> Move to a source and package release model

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/packaging_test_pull_request_deb.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/packaging_build_deb_coreproject.yaml
ee7f1c6269609e612b50b7acb90e9b1e170d7b61 moved the foreman jobs around. This allows the Debian package building to use those new jobs.
=> Update Debian building to new job names

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/foreman.groovy
The source release job is failing because the database name is too long. test-foreman-develop-source-release-11-ruby-2-5-mysql-development is 65 characters while the limit is 64.
=> Shorten the database names

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/packaging_test_pull_request_deb.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/packaging_build_deb_coreproject.yaml
37b6224fbc1ca5cea9e92eb3fdec8dbc06727e0e renamed the jobs but omitted the change to Debian jobs.
=> Adjust Debian jobs to the new package naming conventions

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/foreman_packaging_release.groovy
not only set concurrent:false but also add disableConcurrentBuilds to
the pipeline definition
the way we currently track "hat has been built" does not allow for
concurrent building
=> disable concurrent builds for foreman-packaging-release

puppet/modules/utility/manifests/init.pp
It's included in the rsync module which leads to duplicate resources. It may be possible to include the rsync class here, but that might result in other duplicate resources.
e58d934e00f51531880ce534ae344edbf3cd9e60 introduced this change so it's safest to revert it for now.
=> Do not include rsync in utility

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/packaging_build_deb_coreproject.yaml
Currently these jobs still build tarballs and are package sources so they should be allowed.
=> Allow -package-release jobs as sources

puppet/modules/jenkins_job_builder/files/theforeman.org/unmanaged_jobs.rb
Previously it stripped the scheme. That meant it fell back to HTTP which does a redirect to HTTPS. This raised an error instead of the intended operation. By including the scheme, net/http can perform the correct request.
=> Handle HTTPS in unmanaged_jobs.rb

deploy/config/deploy/yum.rb
Now that yum.theforeman.org is behind a CDN, we need to push to the actual host which is currently web02.
=> Deploy yum content to web02

ansible/fastly.yml
setting it to / makes the logfiles start with a / which confuses some clients
=> don't set logging path to / but to an empty string

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/rpm_packaging.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/foremanPluginsRelease.groovy
This refactors the pipeline to be driven by configuration and allows changing the versions by just changing the versions hash at the top. The end result is still readable for end users in the same way. It may be even more readable by printing the exception.
It also allows defining multiple distributions which will be useful when we add EL8 support.
=> Refactor plugins pipeline

puppet/modules/jenkins_job_builder/files/centos.org/ansible/jenkins_job.yml
Otherwise, builds that take longer than two hours time out.
Instead of increasing the count I increased the delay between polls - 30
seconds is often enough, 10 seconds extra delay to get the results isn't
too bad and in the case of shorter jobs will reduce the amount of
requests needed.
=> Increase CentOS CI polling timeout

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/foreman-plugins-pull-request.yaml
This job is tested as it were a foreman plugin. That doesn't work.
=> Remove kubevirt hammer job

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/packaging_repoclosure.sh
232dc5f56b5b73a391a844988fe822a48d7784c6 updated to Puppet 6 but Foreman 1.20 and 1.21 are incompatible and need to use puppet 5. Since we only have one in the repoclosure config we'll only enable the one that's actually present.
=> Allow using puppet-5 in repoclosure

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/source/smart-proxy.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_proxy_develop_pr_core.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/test_proxy_develop_pr_core.yaml
Now that the Puppet gem is never included anymore, it's no longer needed to test this. Also adds Ruby 2.6 to the matrix.
=> Remove Puppet from the Smart Proxy testing matrix

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_plugin.sh
Plugins currently enhance jenkins:unit task with all of their tests
including integration tests if present. This causes failures since we no
longer compile webpack by default when running tests. As a side effect,
plugins that do not include integration tests will no longer install
node modules as the previous condition was incorrect - it tested for the
presence of package.json in APP_ROOT (which is foreman core) instead of
PLUGIN_ROOT (which is the plugin's folder).
=> Compile webpack when running integration tests

puppet/modules/jenkins_job_builder/files/centos.org/pipelines/test/luna/nightly.groovy
This is parallel to ec5f182ae9221280bc3983faae5701db78993200 but for luna instead of katello.
=> Use the correct luna server name

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/test/testKatello.groovy
The latest version of `eslint` and most of its plugins dropped the support for node-6/
It will be risky to continue running eslint on node-6.
Instead, I would like to run `eslint` using `.travis` wich is more straight forward to configure in this case.
=> Stop using eslint for katello test

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/client.groovy
In a for(x in y) the variable x is mutable. That means its value changes during the loop. The repoclosure() call uses this variable and thus results in the last value. This iteration doesn't have that issue.
It also fixes an issue where the push loop used the incorrect variable.
=> Use immutable variables

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/pipeline/katello-devel-forklift-test.yaml
The katello dev box job can be out of date and not accurately reflect whether the dev
box will spin up successfully. This commit adds a timed trigger to run the job twice
a day.
=> Adds timed cron to katello dev job

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/foreman-discovery-image.groovy
this avoids Jenkins quoting the input and the wildcards not matching
=> make mv less smart

puppet/modules/web/manifests/init.pp
this should be short enough for release-time checks but also allow the
cache to serve a bit of content before expiring
=> cache normal content of yum.theforeman.org for 2 minutes

puppet/modules/jenkins_job_builder/files/centos.org/ansible/jenkins_job.yml
"result" is populated as soon as all stages finished, but we also want
the post actions to finish, as those may do some post-processing we
depend on (e.g. archiving artifacts)
the "building" entry is a boolean, declaring the overall job state
=> wait for the ci.centos.org job to fully finish

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/debian/stage_packages_plugin.sh
this allows deb.tfm.o to point at a CDN and ssh doesn't care for the
hostname anyways
=> always use web02 as the host to rsync-over-ssh things to

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/release.groovy
we want to move deb.tfm to the cdn at some point
=> push to web02.tfm, not deb.tfm

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/foreman-pipeline.groovy
otherwise it's never properly executed
=> wrap push debs in script

puppet/modules/freight/templates/rsync.erb, puppet/modules/freight/templates/rsync_main.erb
if we run multiple publishes in parallel, it might be that one already
finished the cleanup, so the other would error out trying to delete the
files. let's just ignore errors from the find -delete call.
=> ignore delete errors in freight receive script

puppet/modules/jenkins_job_builder/files/centos.org/pipelines/lib/foremanCentosJob.groovy
not all jobs actually generate junit xml
=> allow empty junit results

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/foreman.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/source/katello.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/test/testKatello.groovy
Katello used to do this individually, but it's easier to be done
directly after calling `bundle install` which we do in configureDatabase
=> always archive Gemfile.lock after installing Foreman dependencies

puppet/modules/web/manifests/init.pp
As a puppet hater, I have to say this is where it pays off.
=> Added docs vhost to web02

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/rvm.groovy
When using parallel pipelines in Jenkins, a single job can run multiple times on the same node. They can be identified by a combination of `BUILD_TAG` (`JOB_NAME`-`BUILD_ID`) and `EXECUTOR_NUMBER`. It can stay simplified if the number is 0. Note they are strings and not integers.
=> Generate a gemset per executor

puppet/modules/slave/manifests/init.pp
It is no longer needed in tests and doesn't install on recent nodejs versions.
=> Drop phantomjs on slaves

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/scm/kafo.yaml
74838a123cb1776aced99aacd656a8a6e651c6d5 rewrote the job to a pipeline but didn't remove the now unused kafo_pr scm definition.
=> Drop kafo_pr scm definition

puppet/modules/jenkins_job_builder/files/centos.org/ansible/jenkins_job.yml
When the build steps pass but the test results fail, it's marked as UNSTABLE. Without this, the code will continue polling until it times out.
=> Handle UNSTABLE as a job result

deploy/config/deploy/yum.rb
repo_dest can contain multiple slashes, so that dirname would still
return some of them, but we actually don't care for the dir/basename,
just for a useful name of the logfile
=> replace all slashes in repo_dest for the rsync log path

puppet/modules/jenkins_job_builder/files/centos.org/jobs/foreman-katello-test.yml, puppet/modules/jenkins_job_builder/files/centos.org/jobs/foreman-luna-nightly-test.yml, puppet/modules/jenkins_job_builder/files/centos.org/jobs/foreman-luna-upgrade-nightly-test.yml, puppet/modules/jenkins_job_builder/files/centos.org/jobs/foreman-nightly-test.yml, puppet/modules/jenkins_job_builder/files/centos.org/jobs/foreman-release-test.yml, puppet/modules/jenkins_job_builder/files/centos.org/pipelines/lib/pipelines.groovy, puppet/modules/jenkins_job_builder/files/centos.org/pipelines/test/foreman/nightly-centos7.groovy, puppet/modules/jenkins_job_builder/files/centos.org/pipelines/test/foreman/nightly-debian10.groovy, puppet/modules/jenkins_job_builder/files/centos.org/pipelines/test/foreman/nightly-debian9.groovy, puppet/modules/jenkins_job_builder/files/centos.org/pipelines/test/foreman/nightly-ubuntu1804.groovy, puppet/modules/jenkins_job_builder/files/centos.org/pipelines/test/foreman/release.groovy, puppet/modules/jenkins_job_builder/files/centos.org/pipelines/test/katello/3.12-upgrade.groovy, puppet/modules/jenkins_job_builder/files/centos.org/pipelines/test/katello/3.12.groovy, puppet/modules/jenkins_job_builder/files/centos.org/pipelines/test/katello/3.13-upgrade.groovy, puppet/modules/jenkins_job_builder/files/centos.org/pipelines/test/katello/3.13.groovy, puppet/modules/jenkins_job_builder/files/centos.org/pipelines/test/katello/3.14-upgrade.groovy, puppet/modules/jenkins_job_builder/files/centos.org/pipelines/test/katello/3.14.groovy, puppet/modules/jenkins_job_builder/files/centos.org/pipelines/test/katello/nightly-upgrade.groovy, puppet/modules/jenkins_job_builder/files/centos.org/pipelines/test/katello/nightly.groovy, puppet/modules/jenkins_job_builder/files/centos.org/pipelines/test/luna/nightly-upgrade.groovy, puppet/modules/jenkins_job_builder/files/centos.org/pipelines/test/luna/nightly.groovy
* a2fd8ac4 Add {install,upgrade}PipelineVars()
All install and upgrade pipelines are the same and this reduces the duplication. It also makes sure that smoker logs are collected in every single pipeline rather than just nightly-centos7.
* 00fd1254 Drop nightly debian9 vars
a1750fa620044620a610ae346ffb3768ea4ad5f3 dropped Debian 9 nightly builds but left this file.
=> Collect smoker logs on all pipelines + refactor

puppet/modules/freight/files/deb-HEADER.html
This removes HTML body tags since Apache already adds those. This also
means the title can't be changed. Dropping these just removes invalid
HTML.
It also stops listing the stable version since that's not being updated
anymore. Users shouldn't be using it.
The versions are updated to list the versions that are actually present.
Lastly it adds a short example, including adding the GPG key.
=> Update the Debian README header

puppet/modules/jenkins_job_builder/files/centos.org/pipelines/lib/pipelines.groovy
d761823e50c707fdb2fca72230f8f374a8abf7b2 unified the code but uses an invalid method. This corrects the mistake.
=> Correctly update the extra_vars in pipelines

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/debian/execute_pbuilder.sh
Starting Foreman 2.0 the convention changed to lowercase. This because Debian was already using lowercase and in RPMs it's also useful because of sorting: RC < develop < rc. That means with lowercase there's no need to bump the release where there is with uppercase.
=> Use lowercase for release candidates

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/smart-proxy-plugin-pull-request.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/smart-proxy-plugin.yaml
The Proxy is now Ruby 2.5+ so these will fail.
=> Do not run Ruby 2.0.0 tests for Smart Proxy Plugins

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/publishers/trigger-release-job.yaml
e0243fbc2170aff4398ef0fcd496be6ce6f98c92 removed the last use of this, but didn't remove the publisher itself.
=> Remove unused publisher

puppet/modules/slave/manifests/postgresql.pp
First attempt at something that works across all our various nodes that run Postgres: CentOS and AWS RHEL. The RHEL on AWS uses RHUI to get it's repositories which have different identifiers than standard RHEL repositories. This also handles removal of older postgresql.
I'm sure there are cleaner ways to handle this logic but I wanted something that I tested and worked to start from. @mmoll @ekohl please tell me how to make this cleaner :)
=> Upgrade to nodes to postgresql12

README.md, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/foreman-x-develop-release.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/source/foreman-installer.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/source/foreman-selinux.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/source/foreman.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/source/hammer-cli-x.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/source/katello.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/source/smart-proxy.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/test/foreman-selinux-develop-test.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release/package/foreman-develop-package-release.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release/package/foreman-installer-develop-package-release.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release/package/foreman-selinux-develop-package-release.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release/package/hammer-cli-foreman-master-package-release.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release/package/hammer-cli-katello-master-package-release.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release/package/hammer-cli-master-package-release.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release/package/katello-master-package-release.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release/package/smart-proxy-develop-source-release.yaml
Since all jobs now follow $project-$branch-source-release, we can rely on those to generate the tarball.
Also cleans up an unused publisher and updates the conventions in README.md.
=> Copy sources in foreman-x-develop-release

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/foreman-x-develop-release.groovy
In https://ci.theforeman.org/job/katello-master-package-release/1020 this works. Previously it [failed](https://ci.theforeman.org/blue/organizations/jenkins/foreman-installer-develop-package-release/detail/foreman-installer-develop-package-release/324/pipeline/54):
```
[2020-02-24T22:38:56.200Z] TASK [copy source files] *******************************************************
[2020-02-24T22:38:56.200Z] An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
[2020-02-24T22:38:56.200Z] failed: [foreman-installer] (item=foreman-installer-2.1.0-develop.tar.bz2) => changed=false
[2020-02-24T22:38:56.200Z]   ansible_loop_var: item
[2020-02-24T22:38:56.200Z] …
```
=> Correctly set nightly_sourcefiles

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/source/foreman-installer.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/source/foreman-selinux.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/source/foreman.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/source/hammer-cli-x.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/source/katello.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/source/smart-proxy.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/test/foreman-selinux-develop-test.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/vars/hammer-cli-foreman-master.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/vars/hammer-cli-katello-master.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/vars/hammer-cli-master.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/vars/katello-master-release.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/vars/smart-proxy-develop-release.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release/source/foreman-develop-source-release.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release/source/foreman-installer-source-release.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release/source/foreman-selinux-source-release.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release/source/katello-master-source-release.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release/source/smart-proxy-develop-source-release.yaml
This also corrects the smart-proxy project_name which fixes its package release job. By making the source and package release use the same vars file, it's much more likely they'll do the same thing.
=> Use vars files in source-release jobs

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/foreman-x-develop-release.groovy
This technically isn't correct since the hammer packages are different, but those are not built for Debian as nightly packages. However, it is more correct than project_name since smart-proxy != foreman-proxy.
=> Use obal_package_name as the debian package name

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/foreman-deb.groovy
In 988fdc857ca6380ca546760112af2489dca84760 I copied lines but forgot groovy doesn't have trailing a trailing comma and introduced this syntax error.
=> Add missing comma

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/source/katello.groovy
Currently the katello source job directory is 30 GB because there are a lot of builds. The older ones are never used and can by safely rotated.
=> Only keep katello sources for a week

puppet/modules/slave/manifests/postgresql.pp
PR from the discussion here: https://community.theforeman.org/t/adding-postgresql-evr-to-jenkins-slaves/17686/6
A couple notes:
The postgresql-evr package isn't available in nightly yet so I put the staging repo in its place.
`init.pp` was mentioned for configuring the repo but it seemed like just using `yumrepo` in `postgresql.pp` would work based on other examples.
=> Add postgresql-evr package and its repo to unit test slaves

puppet/modules/profiles/manifests/jenkins/node.pp, puppet/modules/slave/files/titorc, puppet/modules/slave/manifests/init.pp, puppet/modules/slave/manifests/packaging/rpm.pp, puppet/modules/slave/manifests/swap.pp, puppet/modules/slave/templates/hub_config.erb
The goal of this class is to replace the config group currently used in Foreman. Long term all machines should only be assigned classes from the profiles module and Foreman only imports those classes.
This also removes the hub and copr configs because I believe they are unused.
=> Add a Jenkins node profile

puppet/modules/deploy/files/script.sh
This saves cloning the test_modules and the Ansible submodule.
=> Only clone git_modules in Puppet deployment

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/foreman-plugins-pull-request.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/plugins/foreman_omaha.yaml
This PR removes foreman_omaha from the Jenkins testing as #1017 did not get in. We'll migrate the plugin to Github Actions.
=> foreman omaha: remove ci job

puppet/modules/web/manifests/vhost/deb.pp, puppet/modules/web/manifests/vhost/stagingdeb.pp
20da2b1a98ff33bf8f992d9310620883dcbb601f rewrote the webserve profiles. This broke deb pushing because of the $home variable. 6f8291ad7a3f56c4c77f91aee6064d05cdace3a6 fixed stagingdeb but deb was not fixed correctly. This commit aligns both to use the same method.
=> Fix deb pushing

puppet/modules/slave/manifests/packaging/rpm.pp, puppet/modules/unattended/manifests/init.pp
Working around this issue https://github.com/rpm-software-management/tito/pull/354#issuecomment-613523823
=> Pin tito to 0.6.12 to workaround FetchBuilder issue

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/test_develop_pr_core.yaml
Rails 6 will not work with the sqlite version shipped in EL7. We are
dropping support for it. Nulldb testing is added in a seperate commit.
=> Drop sqlite testing from core PRs

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/pipelines/luna.groovy
upgrade tests can take 3.5 hours to complete.
=> Increase luna timeout to 4 hours

puppet/modules/jenkins_job_builder/files/centos.org/ansible/jenkins_job.yml
Otherwise the polling finishes after ~3 hours, and luna upgrade tests
can take longer.
=> Increase length of centos ci polling

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/source/katello.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/test/testKatello.groovy
This is related to https://github.com/Katello/katello/pull/8722 - which allows us to use the npm dependencies from Foreman when testing. With that change, we need to install dependencies from Foreman in CI.
=> Adds foreman npm install step to Katello

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/foreman-plugins-pull-request.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/plugins/foreman_expire_hosts.yaml
I've opened https://github.com/theforeman/foreman_expire_hosts/pull/63 to migrate tests to GitHub Actions
=> foreman_expire_hosts: remove ci job

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/foreman-plugins-pull-request.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/plugins/foreman_monitoring.yaml
I've opened https://github.com/theforeman/foreman_monitoring/pull/74 to migrate tests to GitHub Actions
=> foreman_monitoring: remove ci job

puppet/modules/jenkins_job_builder/files/centos.org/pipelines/lib/foremanCentosJob.groovy
otherwise we get a string "null" later on
=> set expected version to an empty string if unset

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/test/rpm_packaging.groovy
when picking back to stable branches, this will not always be true
=> only verify release on PRs to develop

puppet/modules/jenkins_job_builder/files/centos.org/centos_jenkins.ini, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/infra/updateJobs.groovy
this updates the URL of the jenkins node, as you can reach the API also
*below* a view, but then are limited to that view -- exactly what we
need to delete only our jobs :)
=> clean old ci.centos.org jobs automatically

puppet/modules/jenkins_job_builder/files/centos.org/jobs/foreman-ci-centos-simple-test.yml
I think this will also fix: https://ci.theforeman.org/job/ci-centos-integration-test/477/console
=> Add parameter to ci-centos integration test to mirror other tests

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/foreman-plugins-pull-request.yaml
https://github.com/theforeman/foreman-tasks/pull/574 is introducing the GH actions, so we don't need to test `foreman-tasks` on Jenkins anymore.
=> Do not test foreman-tasks on Jenkins

puppet/modules/secure_ssh/manifests/receiver_setup.pp, puppet/modules/secure_ssh/manifests/rsync/receiver_setup.pp, puppet/modules/web/manifests/vhost/deb.pp, puppet/modules/web/manifests/vhost/stagingdeb.pp
the main deb user needs to be able to read it.
secrets (ssh, gpg) are still secure as their folders have stricter perms
=> make stagingdeb homedir world-readable

puppet/modules/jenkins_job_builder/files/centos.org/ansible/provision.yml
Based on:
```
+ ansible-playbook -i localhost provision.yml
[WARNING]: Unable to parse /home/foreman/workspace/foreman-pipeline-
katello-3.17-centos7-install/foreman-
infra/puppet/modules/jenkins_job_builder/files/centos.org/ansible/localhost as
an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: Could not match supplied host pattern, ignoring: all
[WARNING]: provided hosts list is empty, only localhost is available
PLAY [localhost] ***************************************************************
TASK [Gathering Facts] *********************************************************
ok: [localhost]
TASK [Get a new node] **********************************************************
fatal: [localhost]: FAILED! => {"msg": "The conditional check …
```
=> Retry provisioning of a ci.centos.org node

vagrant/manifests/default.pp
for some reason, this didn't match my FQDN host today:
Error: Could not find node statement with name 'default' or 'jenkins-master.yatsu.example.com' on node jenkins-master.yatsu.example.com
=> match all jenkins-master nodes

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/ansible.groovy
We had implemented that once already, but then reverted because it
behaved weirdly. I can't reproduce the bad behaviour anymore, so let's
try this again.
Revert "Revert "allow running ansible playbooks in a virtualenv""
This reverts commit ad573df4439ebb33f1c91e29b51815297accb338.
=> allow running ansible playbooks in a virtualenv

puppet/modules/jenkins_job_builder/files/centos.org/ansible/jenkins_job.yml
we only need to know if the job finished at all (or was aborted)
=> stop polling after *any* job result

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/ansible.groovy
otherwise, when running multiple `runPlaybook` with `parallel`, the first
invocation wins and you end up with the same command executed multuple
times instead of the individual ones.
=> fix scoping of the stringifyed command

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/source/katello.groovy
otherwise the built RPM might have the wrong hash in the version
=> don't add foreman changes to katello source release changes

puppet/modules/freight/templates/cron.erb
the old logic always kept "one version" of every package, which can
result in broken PR builds if a user does the following:
1. build package_a with a bug and never builds a fixed version
2. tries to build package_b that depends on package_a
=> remove all user debs after 7 days

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/foreman_infra.groovy
otherwise archiveArtifacts rejects the path
=> use relative path when archiving artifacts

docs/foreman-puppetserver.md, docs/overview.md
Replaces:
* https://projects.theforeman.org/projects/foreman/wiki/Infrastructure
This is scant information to start with as I am porting the wiki pages over first for review, and to allow brain dumps of knowledge.
=> Add Foreman and Overview docs

README.md
To be added once the majority of new docs have been added to `docs/`
=> Add Table of Contents with links

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/release.groovy
3e379fb5d1ef376f0a8e06171de7cd58b4004389 added web01 syncs as optional, but 5f2568a88b3761f5b2d88e6668fccbe30d761a40 removed web02. This means we should not treat failures as fatal.
=> Treat web01 repo failures as fatal

puppet/modules/jenkins_master/manifests/init.pp
We don't use this plugin and it contains an XSS exploit with a patch available.
=> Remove custom-job-icon and cvs plugins from Jenkins

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/test/foreman-installer.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/tests/foreman-installer-pr-test.yaml
Adapts the current state of Travis testing on the foreman-installer project instead to a Jenkins job
=> Add a job to test foreman-installer PRs

koji/collection-mash-split.py
2d26531f97e94d79c23a7ec905b5202f4b992c29 dropped 1.24, but in doing so the tuple changed into simple braces. That means the in check was changed to a substring check. While it may work, it's not really correct and can break later.
=> Fix in check with mashing

koji/collection-mash-split.py
There are various places in the code that have "in [array]" syntax.  This switches to using version comparison logic, to minimize the need to maintain version matricies in the conditionals, and replace them with simple greater than, less than, equal to logic.
=> Switch to using LooseVersion version comparisons

puppet/modules/profiles/manifests/web.pp
@alexjfisher reported having issues to rsync due to "max connections reached"
=> increase max_connections to 10 for rsync downloads

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/release.groovy
this allows for older versions of the plugins to remain in the repo
=> merge pulpcore rpms

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/foreman_infra.groovy
much easier to read than the plain output (or navigating to
ci.centos.org)
=> publish tap results downloaded from cico

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/packaging_test_pull_request_deb.sh, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/packaging_build_deb_coreproject.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/packaging_build_deb_dependency.yaml, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release_nightly_build_deb.yaml
Version 2.0 was the last that supported these, but that's now EOL. This allows us to clean up the unsupported builders.
=> Drop ARM builds

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/rvm.groovy, puppet/modules/slave/manifests/rvm.pp
RVM is not able to install these versions anymore so they're not guaranteed to be available.
This also drops the default Ruby version which forces usage to be explicit about the Ruby version.
Currently this is blocked on https://github.com/theforeman/foreman-infra/pull/1476 which removes the last uses of these RVM versions.
=> Drop old RVM versions

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/rvm.groovy
set +e disables the mode while set -e enables it. This allows it to fail fast when the RVM gemset can't be created.
=> Make withRVM fatal

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/source/foreman.groovy
now that we don't really have more than one DB, there is no need to have the db type in the gemset name
=> shorten DB names to not hit postgresql limits

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/test/foreman-installer.groovy
In newer Kafo versions, --help does not generate an initial empty
log file and thus we should not rely on it for test validation. The
fact that --help does not error should be sufficient.
=> Fix foreman-installer tests that rely on checking for log

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/rvm.groovy
build_tag is defined as "jenkins-${JOB_NAME}-${BUILD_NUMBER}" which
produces too long DB names and the "jenkins" prefix is not really
telling anything as *everything* is run by jenkins here
=> use job_name-build_number instead of build_tag

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/pipelines/foreman-deb.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/pipelines/foreman-pipeline.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/pipelines/foreman-rpm.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/pipelines/katello.groovy
the underlying polling for ci.centos.org is configured for roughly 4h,
so timing this job out earlier is nonsense
=> adjust test pipeline timeouts to 4 hours

puppet/modules/jenkins_job_builder/files/centos.org/pipelines/lib/pipelines.groovy
3d24ecf3695dec14a68458467e075fe651d63b89 renamed the primary box, but forgot the rest of the boxes. This meant that junit.xml was no longer archived.
=> Fix pipeline box names

puppet/modules/jenkins_job_builder/files/theforeman.org/foreman_jenkins.ini, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/infra/updateJobs.groovy
The credentials will need to be created and added if the structure is agreed upon. After this PR, we can then:
* move the creation of this job to the puppet module
* move the bulk of the JJB configurations to a top level directory
=> Add ci.theforeman.org jobs to the update jobs job

puppet/modules/jenkins_job_builder/files/centos.org/pipelines/lib/foremanCentosJob.groovy
in d935d81 we forgot that we can't use writeYaml on ci.centos.org
=> use commandline extra vars on centos ci

puppet/modules/jenkins_job_builder/files/centos.org/pipelines/lib/pipelines.groovy
otherwise you get errors like this:
$ ansible-playbook playbooks/collect_debug.yml -l   -e pipeline_version=3.7 -e pipeline_os=centos8 -e pipeline_type=pulpcore -e foreman_expected_version=
ansible-playbook: error: argument -l/--limit: expected one argument
which is not what we want as a fallback :)
=> fallback to "all" boxes, instead of none

puppet/modules/jenkins_job_builder/files/centos.org/pipelines/lib/foremanCentosJob.groovy, puppet/modules/jenkins_job_builder/files/centos.org/pipelines/lib/pipelines.groovy
in #1547 we made the fallback "all", but also discussed that the whole
if/else logic might be obsolete.
"all" is not a perfect fallback as this also runs collect debug against
other hosts defined in the inventory -- especially the hypervisor we run
our tests on.
however we can use a "pipe-*" pattern to match all hosts belonging to
the pipeline and only fetch data from those.
=> collect debug from all machines that are named pipe-*

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/source/foreman-installer.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/source/foreman-selinux.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/source/foreman.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/source/hammer-cli-x.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/source/katello.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/source/smart-proxy.groovy
package release takes the last successfull source release as the source
for the artifacts, but when we trigger in a stage step, the source
release is not finished yet and package release will take the *previous*
successfull source release as the source, thus not actually building
what it was triggered for.
=> trigger nightly package builds in post

puppet/modules/jenkins_job_builder/files/centos.org/pipelines/foreman-discovery-image-build.groovy
this was disabled in https://github.com/theforeman/forklift/pull/1270, but we forgot the FDI jobs :see_no_evil:
=> install vagrant-scp for FDI jobs

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/pipelines/foreman-deb.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/pipelines/foreman-pipeline.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/pipelines/foreman-rpm.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/pipelines/plugins-deb.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/pipelines/plugins-rpm.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/vars/foreman/2.2.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/vars/foreman/2.3.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/vars/foreman/2.4.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/vars/foreman/nightly.groovy, puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/pipeline/foreman-release-pipelines.yaml
this splits the pipeline definitions into EL and DEB, and uses that to create two plugin tests pipes
if that works as intended, I plan to also split the regular release pipes like this, following what we do in nightly
=> split plugins test pipeline

puppet/modules/slave/manifests/init.pp
the way git annex creates files/folders, they can't be removed by the
owner as the owner lack write permissions to the folders.
=> run jenkins_cleaner as root

puppet/modules/slave/manifests/packaging/debian.pp
this is required to download with pip which we now do :)
=> install pip on debian packaging nodes

koji/flatten-el8/rhel8-split.sh
perl 5.26 is in Base, not AppStream, but thanks to our flattened layout,
we inject 5.30, which overrides 5.26 from base and breaks stuff.
=> kill perl:5.30 from the flattened repos

puppet/modules/freight/templates/cron.erb
nobody really looks at old builds, and 7 days accumulates too much cruft
and eats up diskspace
=> purge debian nightly builds after 3 days

puppet/modules/web/manifests/vhost/web.pp
The idea is to rewrite /api/latest and also /api to the new subdomain.
Do not merge yet, this hasn't been published yet.
=> Modify rewrite rules for apidocs subdomain

puppet/modules/web/manifests/vhost/web.pp
In c7c69ae4ec77d794f536ffe13bb8ea728dd0dba5 the apidoc redirect was made. However, it copied a line with variables and then changed to single quotes. That meant escaping was no longer needed. The result:
```console
$ curl https://theforeman.org/api/2.4/apidoc/v2/compute_profiles/create.html -si | grep Location
Location: https://apidocs.theforeman.org/foreman/$1
```
=> Correct API docs redirect

puppet/modules/freight/files/archivedeb-HEADER.html, puppet/modules/freight/files/deb-HEADER.html
https://blog.jak-linux.org/2021/06/20/migrating-away-apt-key/ describes how a key can be added to /etc/apt/trusted.gpg.d instead of using apt-key.
=> Avoid apt-key in our deb instructions

puppet/modules/web/files/yum/HEADER.html
We've always linked to the foreman-release RPM, but prior to this we only listed EL7. This makes it easier to install the foreman-release RPM on EL8.
=> Add a link to el8/foreman-release.rpm on yum.t.o

puppet/modules/web/files/yum/HEADER.html, puppet/modules/web/files/yum/pulpcore-HEADER.html, puppet/modules/web/manifests/vhost/yum.pp
This explains the intent and support policy for Pulpcore packages.
93e4aa7cc94555dfba124193df7187ccd3428588 started to fix the HTML structure of the existing yum header but left in a spurious body tag. It also updates the version to the latest and adds EL8 examples.
=> Add a header to yum.t.o/pulpcore & update yum.t.o header

puppet/modules/web/files/fastly-purge.sh
https://docs.fastly.com/en/guides/soft-purges
Fixes: 875bb689ce2d52697de7c9a077719f33844143c0
=> Correct typo in Fastly-Soft-Purge header

puppet/modules/slave/files/pbuilder_C10foremanlog, puppet/modules/slave/files/pbuilder_F99printrepos, puppet/modules/slave/manifests/pbuilder_setup.pp
These hooks originated from the Jenkins jobs that would build
debian packages and are added here as they are static for
every build.
=> Add F99printrepos and C10foremanlog hooks for pbuilder

puppet/modules/slave/manifests/init.pp, puppet/spec/classes/slave_spec.rb
the way pbuilder works under the hood, it ends up calling sudo inside
the pbuilder run, and drops the env
=> don't env-reset jenkins when doing sudo

puppet/modules/slave/manifests/pbuilder_setup.pp, puppet/modules/slave/templates/pbuilder_pdebuild.erb
pbulder defaults to storing its build results in `/var/cache/pbuilder/result` (and this is also hardcoded in [1]).
however, when using (p)debuild, you end up having your built debs in the directory above the one you started the build in (= `..`).
due to the fact that we explicitly configure `BUILDRESULT` ([2]) in our pbuilderrc, it tries to copy files to `/var/cache/pbuilder/result` too, which now fails as we don't call pdebuild with sudo anymore.
we can explicitly pass `--buildresult ..` to pdebuild, which will result in a warning, as it tries to copy files to a place they are already present, but otherwise this works well.
I: file ../hello-dbgsym_2.10-2_amd64.deb is already in target, not copying.
I: file ../hello_2.10-2_amd64.buildinfo is already in target, not copying.
I: file …
=> explicitly set buildresult to ..

puppet/modules/slave/templates/pbuilder_f70.erb
This means it's no longer needed to install gnupg which makes it slightly faster.
I should note I didn't test this.
=> Use trusted.gpg.d over apt-key

puppet/modules/deploy/files/script.sh
This creates a .resource_types directory which is needed by Puppetserver to have proper environment isolation. It also helps with changing type signatures like the addition of a parameter.
=> Run puppet generate deploy in deploy-puppet

puppet/modules/deploy/files/script.sh
When puppet runs as non-root, it uses ~/.puppetlabs and the type generation command gets confused:
```console
$ puppet generate types --environment production
Error: no implicit conversion of nil into String
Error: Try 'puppet help generate types' for usage
```
By forcing the root config, it works.
It also speeds up the clone by doing --depth 1 and quiets it.
=> [deploy] Force production config location & speed up clone

puppet/modules/ssh/manifests/init.pp
On a fresh installation the ssh module fails because /root/.ssh doesn't exist and then authorized_keys can't be created. We actually don't need this to be a file at all so we can stop managing it. If we would manage SSH keys, the ssh_authorized_key resource type can create it if needed.
=> Ensure root SSH config provisions correctly

puppet/modules/slave/manifests/packaging/rpm.pp
Since 9cf09d3335079073b9cb45cf342dcf4273a3583b this alias is unused. This is the first step to cleaning it up (#520).
=> Remove kkoji alias

koji/vars/external_repos.yml
Looks like Centos 8.5 don't have the Devel repo ready to use, changing to Vault to ensure that our buildroot runs for EL8
=> Change Devel URL for Centos 8

koji/collection-mash-split.py
if for some reason the comps xml can't be fetched from git, error out
instead of using a stale local copy which can contain a wrong set of
packages
also use `git fetch` over `git pull` to avoid merging problems
=> fail if comps.xml can't be fetched

koji/vars/external_repos.yml
This is an intermittent step to switching our el8 content strategy.
=> Switch from mirror to vault for Centos 8 content.

puppet/modules/slave/manifests/packaging/rpm.pp
Since 70479ed5b2cec0e653321d4dcda564cdc4061eb7 this is ensured absent. By now it has propagated to all machines and can be dropped.
Fixes #520
=> Drop bin/kkoji file definition

puppet/modules/freight/files/deb-HEADER.html, puppet/modules/freight/files/stagingdeb-HEADER.html
This updates the headers to have the current Debian versions and introduces an easy copy-paste example using /etc/os-release.
=> Update (staging)deb.theforeman.org HEADER.html

puppet/modules/web/files/deploy-yumrepo.sh
when merging a fresh repo, there is only one modules.yaml.gz present
and that already gets removed by modifyrepo_c in the previous step.
=> don't fail if there is no moduledata to remove

Vagrantfile
CentOS Linux 8 is EOL and no longer installable.
=> Use CentOS Stream 8 for Vagrant jenkins-node-el8

puppet/modules/slave/manifests/rvm.pp, puppet/modules/slave/manifests/rvm_config.pp
No job uses this anymore. The Ruby 2.4 config is still used by Kafo.
For now this is untested, but submitting this while I test it out.
=> Remove Ruby 2.6 RVM config

ansible/fastly.yml
the BWI one does not offer shielding anymore. this change was
automatically performed on our account by Fastly, just updating our
config to match.
See https://status.fastly.com/incidents/ysgcxswp5h8l for details.
=> update fastly shielding to IAD datacenter

puppet/modules/slave/manifests/init.pp
Jenkins 2.361.1 has started to require Java 11. On Debian this is already the default, but the puppetlabs-java module defaults to OpenJDK 1.8.0 on EL.
=> Update Java to 11 on Jenkins nodes

puppet/modules/slave/manifests/init.pp
Jenkins should use Java 11, so 1.8 is no longer needed. Having it installed may mean it's used accidentally.
Fixes: 2cdc68e4c86cac88cb350d776ff52df4547e4c7c
=> Remove Java 1.8 on Jenkins nodes

puppet/modules/slave/manifests/init.pp
Puppet uses rpm -e to remove packages rather than yum, so removing the leaf package doesn't work since it's still needed by others. This lists all java packages that need to be removed.
Fixes: 7e3425cfb7d6193d32ab0f32ed311c150155ed7a
=> Remove all Java 1.8 packages from Jenkins nodes

koji/collection-mash-split.py
Making sure that EL9 is added for >= 3.18, and EL7 is only added for release <= 3.18
=> Update mash Pulpcore 3.21

puppet/modules/secure_ssh/manifests/receiver.pp, puppet/modules/secure_ssh/manifests/rsync/receiver.pp, puppet/modules/secure_ssh/manifests/rsync/uploader.pp, puppet/modules/secure_ssh/manifests/uploader.pp
`validate_hash` is deprecated in favor of native data types. Also uses puppet-strings documentation.
=> Remove deprecated coding styles

puppet/spec/spec_helper.rb
=> Drop Debian 9 & 10 support in our Puppet infra

puppet/spec/spec_helper.rb
I forgot Discourse still runs on a Debian 9 install.
Fixes: 1607af1e0fc232a6176691640cbb3387fca4ab04
=> Add Debian 9 back

puppet/modules/profiles/manifests/web.pp, puppet/modules/ssh/lib/puppet/parser/functions/ssh_keygen.rb, puppet/modules/web/manifests/vhost/archivedeb.pp, puppet/modules/web/manifests/vhost/deb.pp, puppet/modules/web/manifests/vhost/downloads.pp, puppet/modules/web/manifests/vhost/stagingdeb.pp, puppet/modules/web/manifests/vhost/web.pp, puppet/modules/web/manifests/vhost/yum.pp, puppet/spec/classes/profiles_web_spec.rb
Rather than hardcoding it to /etc/puppet (which doesn't exist on a Puppet AIO install) this uses the vardir setting. This works well for extlib::cache_data. As an additional benefit it can now run this in tests on a non-privileged user.
=> Generate SSH keys in Puppet's vardir

puppet/modules/slave/files/pbuilder_F67-add-puppet-repos
We've updated develop to puppet-strings 3.x which requires Ruby 2.7.  Puppet 6 ships Ruby 2.5 while Puppet 7 has 2.7.
=> Switch Debian package building to Puppet 7

puppet/modules/profiles/manifests/web.pp
This redirects 3.6 to nightly, which will be the next Foreman version once we branch.
=> Mark Foreman 3.6 as the next version

puppet/modules/slave/manifests/rvm.pp
Ruby 2.7.4 bundles 3.1.6. In CI we're seeing issues with Gem::NameTuple and 3.1.3 does have a minor enhancement that may solve it:
> Resolver: require NameTuple before use
It's unclear why we didn't see these failures before.
=> Update Rubygems to 3.1.6 for Ruby 2.7

puppet/modules/profiles/manifests/base.pp
Previously we ran chrony on EL7, but the bulk of the hosts didn't use this base profile yet so it wasn't noticed. After the migration this started to show up.
Because it ran on some hosts, this also includes code to remove ntp from the system.
Fixes: e519403be6959247ab8632599dfc1edaa51c2e90
=> Use chrony on EL7 too

puppet/data/common.yaml
Right now Puppet emails for every run:
```
/opt/puppetlabs/puppet/cache/lib/puppet/type/gnupg_key.rb:91: warning: URI.escape is obsolete
/opt/puppetlabs/puppet/cache/lib/puppet/type/gnupg_key.rb:102: warning: URI.escape is obsolete
/opt/puppetlabs/puppet/cache/lib/puppet/type/gnupg_key.rb:91: warning: URI.escape is obsolete
/opt/puppetlabs/puppet/cache/lib/puppet/type/gnupg_key.rb:102: warning: URI.escape is obsolete
/opt/puppetlabs/puppet/cache/lib/puppet/type/gnupg_key.rb:91: warning: URI.escape is obsolete
/opt/puppetlabs/puppet/cache/lib/puppet/type/gnupg_key.rb:102: warning: URI.escape is obsolete
```
While that should be resolved properly, using the systemd timer should avoid a bunch of emails.
Currently testing this out.
=> Switch the Puppet runmode to systemd.timer

puppet/manifests/site.pp
Previously it was assumed all nodes have nodeXX but we also have deb-nodeXX.
Fixes: 6cbe2656dd605d22475cc4dcdf5fc3f84d0d3072
=> Match deb-node01 in site.pp

puppet/data/common.yaml, puppet/manifests/site.pp
Prior to this we had this information in the Foreman ENC, but now it's included in Hiera. A possibly better solution would be to search for the correct hostnames using a foreman lookup, but since we don't migrate that often this is good enough for now.
=> Include backup configuration

puppet/modules/foreman_debug_rsync/manifests/config.pp, puppet/modules/foreman_debug_rsync/manifests/cron.pp, puppet/modules/foreman_debug_rsync/manifests/init.pp, puppet/modules/secure_ssh/manifests/receiver_setup.pp, puppet/modules/secure_ssh/manifests/rsync/receiver_setup.pp, puppet/modules/secure_ssh/manifests/rsync/uploader_key.pp, puppet/modules/secure_ssh/manifests/uploader_key.pp, puppet/modules/slave/manifests/init.pp, puppet/modules/slave/manifests/packaging.pp, puppet/modules/slave/manifests/pbuilder_setup.pp, puppet/modules/slave/manifests/rvm.pp, puppet/modules/slave/manifests/swap.pp, puppet/modules/slave/manifests/unittests.pp
Locally I have voxpupuli-puppet-lint-plugins installed. This causes additional plugins to load. These rules are stricter and our CI doesn't catch these. This prepares the code base to include these.
=> Make more modules puppet-lint clean with stricter plugins

puppet/modules/deploy/files/script.sh
g10k defaults to /tmp/g10k, which should be considered insecure. This uses one that isn't shared with other users.
Also pleases shellcheck.
=> Use user's own cache directory for g10k & shellcheck the script

puppet/modules/profiles/manifests/jenkins/node.pp
This avoids the following error:
default expression for $koji_certificate tries to illegally access not yet evaluated $koji_certificate
Fixes: ad305563f6b361fee11d43558b65ae920f61e27f
=> Avoid name collision issue with koji_certificate

puppet/modules/profiles/manifests/base.pp, puppet/modules/profiles/manifests/jenkins/node.pp
This means it'll be present on all our machines.
=> Move REX user management to the base profile

puppet/modules/slave/manifests/unittests.pp
This is needed for at least libyaml-devel.
=> Enable rhel-7-server-rhui-optional-rpms on EL7 RHEL builders

puppet/modules/jenkins_job_builder/templates/jenkins_jobs.ini.erb, puppet/modules/jenkins_master/manifests/init.pp
In b1b5188f3d9d5c037c44ae37a140066f9348e6b7 the directory layout was changed, but the config looked at the old path. This meant that it started to fail when we renamed some files.
Also makes jenkins_master puppet-lint clean, since I opened that file and my editor started to yell at me.
=> Reflect the correct path in jenkins-jobs

puppet/data/common.yaml, puppet/modules/jenkins_job_builder/manifests/config.pp, puppet/modules/jenkins_job_builder/manifests/init.pp, puppet/modules/jenkins_job_builder/manifests/install.pp
The YAML package name has changed. It now also ensures git is installed and stops ensuring python-jenkins explicitly, relying on pip to do dependency resolution for us.
It pins to version 4.3.0, which is the last version before 5 given that Foreman's jenkins-jobs repository is not compatible with it. I started https://github.com/theforeman/jenkins-jobs/pull/329 but that's bigger than I thought so it pins for now.
=> Ensure jenkins_job_builder is EL9 compatible

Vagrantfile, puppet/data/vagrant.yaml, vagrant/hiera.yaml, vagrant/manifests/default.pp
The initial goal was to allow setting the password via Hiera, but then I figured that this also closer aligns the actual deployments. At some point it may be possible to use the same manifest file for both production and vagrant.
This does leak some Vagrant details into the deployed production environment. That could be mitigated by excluding the vagrant.yaml file, but it's not that big of a deal.
=> Sync Hiera in Vagrant & move node config to it

puppet/modules/profiles/manifests/discourse.pp
This doesn't work and it's just a single directory at the moment.
=> Avoid globs in backup paths

puppet/modules/slave/manifests/packaging/rpm.pp, puppet/modules/unattended/manifests/init.pp
We've stopped using this and can be cleaned up.
=> Remove tito from our RPM builders

puppet/modules/slave/manifests/packaging/rpm.pp, puppet/modules/unattended/manifests/init.pp
This reverts commit 61cca97c19bf28c93bc952e3f573f66040c459a7.
I forgot pulpcore-packaging was still using the tito method :/ Let's put this back and I will work on swapping it over.
=> Revert "Remove tito from our RPM builders"

puppet/modules/profiles/manifests/web.pp
It went GA quite a while back and and this makes sure the latest symlinks redirect to the correct version.
=> Declare Foreman 3.7 as stable

puppet/modules/slave/manifests/packaging/debian.pp
Previously there were builders on Debian < 11, but those have been retired and we can simplify the code to just current Debian.
=> Drop conditionals for Debian packaging for non-d11

puppet/modules/web/manifests/vhost/stagingyum.pp
This should setup this up more properly and fix the key mismatch issue.
=> Use rsync::receiver_setup for stagingyum

docs/webserver.md, puppet/modules/web/files/stagingyum/HEADER.html, puppet/modules/web/files/stagingyum/robots.txt, puppet/modules/web/manifests/init.pp
Is this enough to get a DNS entry for `stagingyum.theforeman.org` or do I need @ekohl / @evgeni to add one?
=> Add updated HEADER, and missing stagingyum entries

puppet/manifests/site.pp
=> don't apply redmine profile for redmine01.conova for now

puppet/modules/web/files/deploy-yumrepo.sh
Adds a parameter that can be used to trigger a push from stagingyum to yum. 
The idea being we can keep this script in tact and selectively tell it to deploy from koji (default) or stagingyum.
=> Allow yumrepo to deploy from stagingyum

puppet/modules/slave/manifests/packaging/rpm.pp, puppet/modules/unattended/manifests/init.pp
By now Pulp has also converted and we can really remove tito.
This reverts commit 636eae9f62184865cceb41aa54142d08a5de7f11.
=> Revert "Revert "Remove tito from our RPM builders""

puppet/modules/secure_ssh/manifests/rsync/uploader_key.pp, puppet/modules/secure_ssh/manifests/uploader_key.pp, puppet/modules/slave/manifests/packaging/rpm.pp
I thought the naming was the issue with why the key in the `authorized_keys` was not matching the key on the Jenkins nodes but not the case. Thus I created an unused key and this allows cleaning it up.
=> Allow and remove old yumstage key

puppet/modules/profiles/manifests/web.pp
Foreman 3.8 has branched a while back and this reflects that nightly is now 3.9.
=> Set the next version to Foreman 3.9

puppet/modules/web/files/yum/HEADER.html
Often I want to quickly get the URL for the nightly foreman-release to test out some changes. This makes it easier. It also documents Katello's release repos. To make it a bit easier to see, the Foreman section is shortened.
=> Update yum header to list more URLs

puppet/modules/deploy/files/script.sh
When installing a new module it maintains the file timestamps from the original tarball. puppet generate types uses the timestamp of when it ran.
If you update a module to a release that was created before it ran puppet types generate, it will never update the types. This can happen with a module downgrade, or just when you regenerated types manually. By using --force the timestamps are ignored.
=> Use --force with puppet generate types

puppet/modules/web/files/downloads-HEADER.html
Current support info on https://downloads.theforeman.org/ is outdated.
Let's link to the Support page so that we don't have to update it every time we change something regarding Support.
=> Fix support info on the Downloads page

puppet/modules/unattended/manifests/init.pp
this breaks the whole update transaction and *NO* updates are applied
=> exclude kmod updates, they can depend on newer kernels

Vagrantfile, puppet/data/common.yaml, puppet/data/vagrant.yaml, puppet/manifests/site.pp, puppet/modules/profiles/manifests/repo/rpm.pp, puppet/modules/web/files/rpm/pulpcore-HEADER.html, puppet/modules/web/files/rpm/robots.txt, puppet/modules/web/files/stagingrpm/robots.txt, puppet/modules/web/manifests/vhost/rpm.pp, puppet/modules/web/manifests/vhost/stagingrpm.pp, puppet/modules/web/manifests/vhost/stagingyum.pp, puppet/modules/web/templates/deploy-rpmrepo.sh.epp, puppet/modules/web/templates/deploy-stagingrpm.sh.epp, puppet/modules/web/templates/rpm/HEADER.html.epp, puppet/modules/web/templates/stagingrpm/HEADER.html.epp, vagrant/manifests/default.pp
This is to provide the code to match the structure -- https://github.com/theforeman/foreman-infra/issues/1937
=> Add rpm repo profile

puppet/modules/profiles/lib/facter/external_ips.rb
ipv4.icanhazip.com has an AAAA record, and ipv6 has an A record, which
leads to both facts returning v6 addresses.
while this is a missconfiguration on the side of icanhazip.com, we can
prevent it from happening by forcing things at the resolver level.
=> explicitly resolve A/AAAA when pulling external IP from icanhazip

ansible/fastly.yml
=> set sni_hostname for Fastly

puppet/data/vagrant.yaml, puppet/modules/profiles/manifests/repo/deb.pp, puppet/modules/profiles/manifests/repo/rpm.pp, puppet/modules/profiles/manifests/web.pp, puppet/modules/web/manifests/init.pp, puppet/spec/classes/profiles_web_spec.rb
if you need to disable https, use hiera to disable it on the web class
directly
this allows including the web class multiple times, without having to
care that only one includer can pass args
=> simplify https handling by dropping the profile parameter

puppet/modules/freight/manifests/user.pp
deb.tfm.o (and friends) do not point to our host these days, but to a
CDN, thus, using deb.tfm.o as the vhost name is a tad wrong.
this change introduces two aliases for the vhost: deb-backend.tfm.o and
deb.${fqdn}, which in my test environment results in:
ServerName deb.theforeman.org
ServerAlias deb-backend.theforeman.org
ServerAlias deb.repo-deb.tanso.example.com
This has the benefit that the right vhost is reachable without any
tricks, and will allow us to switch the CDN config to a "more correct"
naming scheme, later dropping deb.tfm.o from the vhost here totally.
(This has the side-benefit that deb.tfm LE requests go via the CDN and
only then hit our box, which is confusing to say the least and that
would stop)
=> add backend serveraliases to debian vhosts

puppet/data/common.yaml, puppet/manifests/site.pp, puppet/modules/profiles/manifests/website.pp, puppet/modules/web/manifests/vhost/downloads.pp, puppet/modules/web/manifests/vhost/web.pp, puppet/spec/classes/profiles_website_spec.rb
- **add backend servername to web vhost**
- **add backend name to downloads vhost**
- **add dedicated website profile for web + downloads**
=> clean web profile

ansible/fastly.yml
We disabled logging in c2b136c7c26053c1e300a37676878fbdfada2bbe, but the
(unused) condition and the empty cloudfiles definition was kept.
Drop them!
=> drop old fastly logging remains

ansible/fastly.yml
- **allow using a different backend name than service name**
- **use backend-names for downloads and deb**
=> move fastly setup to backend naming

ansible/fastly.yml
- **allow setting domains manually**
- **allow configuring healthcheck path**
- **add web service to fastly setup**
=> add web service to fastly setup

puppet/modules/freight/manifests/user.pp, puppet/modules/web/manifests/vhost/archivedeb.pp
there is nothing to be cleaned up, so it just wastes a lot of resources
as archivedeb is rather big
=> disable freight cron for archivedeb

puppet/modules/web/manifests/vhost/stagingyum.pp, puppet/modules/web/manifests/vhost/yum.pp
it's now served to fastly via the backend name
=> drop serveraliases for yum/stagingyum

puppet/modules/jenkins_node/files/pbuilder_F66-add-nodesource-repos
As part of [dropping NodeJS 14](https://community.theforeman.org/t/drop-debian-11-ruby-2-7-and-nodejs-14-support-in-foreman-3-14/40503) this updates nodesource to NodeJS 18. That's also the version included in Ubuntu 24.04.
It drops the conditionals for Foreman < 3.9 since those are gone now.
=> Update NodeJS to 18.x on Ubuntu with Foreman 3.14+

puppet/Gemfile, puppet/modules/jenkins_node/manifests/init.pp, puppet/modules/jenkins_node/manifests/pbuilder_setup.pp, puppet/modules/redmine/manifests/init.pp, puppet/modules/web/manifests/vhost/rpm.pp, puppet/modules/web/manifests/vhost/stagingrpm.pp, puppet/modules/web/manifests/vhost/stagingyum.pp
this effectively updates puppet-lint from 2.5 (ugh!) to 5.1:
```
-    puppet-lint (2.5.2)
-    puppet-lint-absolute_classname-check (3.1.0)
-      puppet-lint (>= 1.0, < 4)
-    puppet-lint-classes_and_types_beginning_with_digits-check (1.0.0)
-      puppet-lint (>= 1.0, < 3.0)
-    puppet-lint-empty_string-check (1.0.0)
-      puppet-lint (>= 1.0, < 3.0)
-    puppet-lint-file_ensure-check (1.1.0)
-      puppet-lint (>= 1.0, < 4)
-    puppet-lint-leading_zero-check (1.1.0)
-      puppet-lint (>= 1.0, < 4.0)
-    puppet-lint-legacy_facts-check (1.0.4)
-      puppet-lint (~> 2.4)
-    puppet-lint-strict_indent-check (2.1.0)
-      puppet-lint (>= 1.0, < 4)
-    puppet-lint-topscope-variable-check (1.2.0)
-      puppet-lint (>= 2.0, < 4)
-    puppet-lint-trailing_comma-check (1.0.0)
- …
```
=> update puppet-lint plugins to allow puppet-lint 5.x
