puppet/modules/jenkins_job_builder/files/config/scripts/deploy_katello_site.sh
puppet/modules/jenkins_job_builder/files/config/yaml/builders/deploy_katello_site.yaml
puppet/modules/jenkins_job_builder/files/config/yaml/jobs/deploy_katello_site.yaml
puppet/modules/jenkins_job_builder/files/config/yaml/scm/katello.org.yaml

First attempt at converting a job over. I picked something simple that has no other job dependencies to get my feet wet.

Add JJB version of deploy_katello_site

---

puppet/modules/debian/manifests/init.pp
puppet/modules/freight/files/deb-HEADER.html
puppet/modules/freight/manifests/install.pp
puppet/modules/jenkins_job_builder/files/config/yaml/jobs/packaging_build_deb_coreproject.yaml

And also some minor other things, please check esp. the change to wheezy in puppet/modules/freight/manifests/install.pp

add Debian/jessie build support

---

puppet/modules/jenkins_job_builder/files/config/yaml/jobs/plugins/foreman_remote_execution.yaml
puppet/modules/slave/manifests/init.pp
puppet/modules/slave/templates/test_pull_requests_foreman_remote_execution.json.erb

Just guessing how to do this based on how other plugins are setup. :sheep:

Add foreman_remote_execution plugin

---

puppet/modules/jenkins_job_builder/files/config/yaml/jobs/plugins/foreman_host_rundeck.yaml
puppet/modules/slave/manifests/init.pp
puppet/modules/slave/templates/test_pull_requests_foreman_host_rundeck.json.erb

I haven't created the test jobs yet, if this is ok I'll create tests with the same names.

Add test_host_rundeck plugin

---

puppet/modules/slave/manifests/init.pp

2.1.5 is coming with Debian/jessie and 2.2.2 is the lastest 2.2.
The rest is just to appease puppet-lint.

bump Ruby 2.1 and 2.2 versions

---

puppet/modules/debian/manifests/init.pp
puppet/modules/slave/manifests/init.pp
puppet/modules/utility/manifests/init.pp

Some fixes from running our slave modules on two new ARM builders.

ARM slave support

---

puppet/modules/web/manifests/init.pp

SSIA
It's this one: http://yum.theforeman.org/plugins/nightly/

Created nightly symlink in releases dir for easier shell scripts

---

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/clone_repository.sh
puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/gemset_cleanup.sh
puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_plugin.sh
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/builders/clone_repository.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/builders/test_plugin.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/deploy_deb.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/systest_foreman.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/test_plugin_matrix.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/wrappers/abort_build.yaml

Test plugin matrix

---

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/clone_foreman.sh
puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_katello.sh
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/builders/clone_foreman.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/builders/test_katello.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/test_katello_core.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/properties/github_katello.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/scm/katello.yaml

Add test_katello_core

---

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/plugins/foreman_remote_execution.yaml
puppet/modules/slave/templates/test_pull_requests_foreman_remote_execution.json.erb

Test foreman_remote_execution against develop

---

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/packaging_repoclosure.sh
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/packaging_repoclosure.yaml

and removing openscap from being used by default

adding predefined lookaside support for repclosure

---

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release_nightly_push_deb.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release_nightly_test_deb.yaml

I don't know if that's sufficient...

remove wheezy and precise from nightly builds

---

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_katello.sh
puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_plugin.sh

Updating katello test configuration

---

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/test_hammer_cli_foreman.yaml

Dependent on https://github.com/theforeman/foreman-packaging/pull/1212

Fixes #15595 - Do not test with Jenkins on 1.9.3

---

puppet/modules/slave/templates/test_pull_requests_foreman_expire_hosts.json.erb
puppet/modules/slave/templates/test_pull_requests_foreman_host_extra_validator.json.erb

@domcleal : Would you mind setting up hooks for the repos as well? I don't have sufficient permissions to to it myself.

ci: add pr testing for expire_hosts & host_extra_validator

---

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_develop.sh
puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_plugin.sh

This will allow running tests on PRs that need npm modules.

run npm install if package.json is present

---

puppet/modules/slave/manifests/init.pp

see http://ci.theforeman.org/job/packaging_build_deb_coreproject/arch=armv7,label=debian,os=jessie/3727/console

install unzip on jenkins slaves

---

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/plugins/foreman_discovery.yaml

I am shooting in the dark here.

Updated stable discovery version to 8.0

---

puppet/modules/debian/templates/pbuilder_f70.erb

1. https://github.com/theforeman/foreman-packaging/issues/1491
1. this
1. https://github.com/theforeman/foreman-packaging/issues/1492

Add Puppet PC1 repository to pbuilder

---

puppet/modules/slave/manifests/init.pp

Attempt number 2 for shutting yum-cron up. See https://docs.puppet.com/puppet/latest/types/yumrepo.html#yumrepo-attribute-descr for details.

Change name param to descr in yumrepo

---

puppet/modules/web/manifests/init.pp

Pending documentation for these - https://github.com/theforeman/theforeman.org/commit/47510d126cb452ed47d7c9572ef0c3349fc8459a

Update latest/next documentation versions for 1.15

---

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/plugins/foreman_discovery.yaml

Is it okay to keep N-1 stable version? @dLobato

Added discovery 9.0 job

---

puppet/modules/web/manifests/init.pp

To be merged after 1.15.0 is announced

Update $stable on web to 1.15

---

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_develop.sh
puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_plugin.sh

5.0.0 is having some problems installing some of our dependencies 
as explained in http://projects.theforeman.org/issues/19717

Pin npm to < 5.0.0

---

.gitmodules

this brings the theforeman modules up to the level of the 1.10 installer

Puppet module update (theforeman modules)

---

puppet/modules/users/manifests/account.pp
puppet/modules/users/manifests/init.pp
puppet/modules/users/manifests/slave.pp

I've also removed some automatic requires file parent directories and users.

Make the users module puppet-lint clean

---

puppet/modules/freight/manifests/config.pp
puppet/modules/freight/manifests/init.pp
puppet/modules/freight/manifests/install.pp
puppet/modules/freight/manifests/user.pp

See individual commits for details

Freight cleanups

---

puppet/modules/awstats/manifests/init.pp
puppet/modules/awstats/manifests/vhost.pp
puppet/modules/awstats/templates/awstats.conf.erb
puppet/modules/awstats/templates/cron.erb

This has already been applied to Web02 using "puppet apply" while developing it, so it should be fine. Resulting output is viewable at http://downloads.theforeman.org/awstats

Add AWStats module for web02

---

puppet/modules/redmine/manifests/init.pp
puppet/modules/redmine/templates/database.yml.erb
puppet/modules/redmine/templates/git_repos.sh
puppet/modules/redmine/templates/logrotate.erb
puppet/modules/redmine/templates/postgresql_backup.sh

Really hacky initial commit for a Redmine module. Mostly compiled while working on the migration to Scaleway today. Lots we can improve, especially in passing parameters from Foreman, but at least it's a start.

Initial import of Redmine config module

---

puppet/modules/redmine/manifests/init.pp
puppet/modules/redmine/templates/secure_config.yaml.erb

Part1 of deploying the tokens from Foreman. Once this is on disk i'll update the redmine repo to use it.

Deploy secure config from Foreman params

---

puppet/modules/web/files/filter_apache_stats.sh

turns out the "bad" behaviour is intended here

revert part of the change in filter_apache_stats

---

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/plugins/foreman_discovery.yaml

Added discovery 10.0 job

---

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/test_develop_pr_core.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/test_plugin_matrix.yaml

Implementing the matrix reduction from https://groups.google.com/forum/#!searchin/foreman-dev/reducing$20test$20matrix%7Csort:relevance/foreman-dev/BT0C9Rd-8cY/P5h3fJHZDAAJ

Update test_develop matrix

---

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/katelloRelease.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release/katello-nightly-release.yaml

Another type of job being moved to a Jenkins pipeline for comment and thought.

Re-factor katello release pipeline

---

puppet/modules/slave/manifests/init.pp
puppet/modules/slave/templates/copr.erb

@GregSutcliffe Check me if I am wrong in how we handle configuring files with secrets here. I think these then get defined in our Foreman instance?

Add copr config template

---

puppet/modules/slave/manifests/init.pp

The name is invalid according to yum.

Set the description rather for google-chrome

---

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/ansible.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/tfmROR51.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/test/tfmROR51.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/test/tfmROR51CoprCleanup.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/packaging/tfm-ror51-cleanup-copr.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/packaging/tfm-ror51-pr-test.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release/tfm-ror51-release.yaml

Add tfm-ror51 scratch build testing on PRs

---

ci

Per -dev thread, attempting to move the jobs to a more obvious location for management of them. I assume this will just work with the symlink.

Move CI jobs folder to top-level

---

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/tfmROR51.groovy

to fix the [pipeline release job](http://ci.theforeman.org/job/tfm-ror51-release/50/console)

Skip looking for packages to build

---

puppet/modules/slave/manifests/init.pp

Offers an alternative to https://github.com/theforeman/foreman-infra/pull/392

Install chromium from EPEL

---

puppet/modules/freight/manifests/user.pp

this should fix issues with the CDN serving old Packages files

set Cache-Control for (staging)deb.theforeman.org

---

puppet/modules/prprocessor/manifests/init.pp

This is untested but it should mostly cover what we have now.

Add a profile for the prprocessor

---

puppet/modules/prprocessor/manifests/init.pp

These were found while deploying

Fix issues in prprocessor

---

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/foremanRelease.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/katelloRelease.groovy

@ekohl another fix required for the pipelines

Update to use new boxes location for Release jobs

---

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/foremanPluginsRelease.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/packaging_build_deb_coreproject.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/packaging_build_deb_dependency.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release_push_deb.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release_test.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/test_1_17_stable.yml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/test_proxy_1_17_stable.yaml

Do not merge as this is work in progress.

Update jenkins jobs for 1.17

---

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/plugins/foreman_discovery.yaml

Preparing 11.0 release, thanks.

Bumped discovery to v11

---

puppet/modules/web/manifests/init.pp

~~Please do not merge as this is wip.~~

Update for 1.17 - point $latest and $next to new versions

---

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/git.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/obal.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/rpm_packaging.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/packaging/foreman-packaging-rpm-pr-test.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/triggers/github_pr.yaml

the code is based on tfmROR51.groovy, which should also migrate to this
new lib as soon as obal supports copr properly

allow for packaging being tested in a pipeline

---

.travis.yml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release_nightly_test_deb.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/test_1_15_stable.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/test_1_16_stable.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/test_1_17_stable.yml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/test_develop.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/test_hammer_cli_foreman.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/test_kafo_master.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/test_plugin.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/test_proxy_1_15_stable.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/test_proxy_1_16_stable.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/test_proxy_1_17_stable.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/test_proxy_develop.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/test_proxy_plugin.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/triggers/schedule_failed_builds.yaml
puppet/modules/jenkins_job_builder/manifests/init.pp
puppet/modules/jenkins_job_builder/manifests/install.pp

use upstream jjb and drop the use of schedule-failed-builds

---

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/rpm_packaging.groovy

* remove trailing newline using .trim()
* quote changed_packages, they might contain newlines

fix sh calls in rpm_packaging.groovy

---

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/packaging_repoclosure.sh
puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/systest_foreman.sh
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/packaging_repoclosure.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release_nightly_test_deb.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release_test.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/systest_foreman.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/systest_foreman_mysql.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/systest_foreman_puppet_nightly.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/systest_foreman_puppet_pc1.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/systest_foreman_umask_077.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/scm/foreman-bats.yaml

Here just so it's not just on my laptop. Feel free to give some early feedback, but this is not tested at all.

Rewrite systests to forklift

---

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/systest_foreman.sh

Remove --foreman-log-level

---

.gitmodules
puppet/modules/slave/manifests/docker.pp
puppet/modules/slave/manifests/init.pp

This is untested and a bit of a leap of faith that the module will just work and configure the slaves that can support docker properly for us. According to (https://github.com/puppetlabs/puppetlabs-docker#description) this should configure on most of our slaves and I assume ignore the ARM slaves. This is my first time trying to add additional puppet modules to our infrastructure so please be gentle and let me know what thoughts are towards any additional config this might need.

Add docker module and configure slave to install and run docker

---

puppet/modules/slave/manifests/init.pp

Unsure about the `;` char at the end, copy-pasted from above.
This syntax kills me.

Added systemd-devel CI dependency

---

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/puppetDeploy.groovy

Without this Jenkins doesn't know what to poll.

Fix SCM polling in puppet-deploy

---

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/rpm_packaging.groovy

filter the deletions from the diff using `--diff-filter=d`

don't try to build removed packages

---

.travis/jjb.sh
ci
puppet/modules/jenkins_job_builder/.gitignore
puppet/modules/jenkins_job_builder/files/centos.org/.gitignore
puppet/modules/jenkins_job_builder/files/centos.org/ansible/ansible.cfg
puppet/modules/jenkins_job_builder/files/centos.org/ansible/deprovision.yml
puppet/modules/jenkins_job_builder/files/centos.org/ansible/provision.yml
puppet/modules/jenkins_job_builder/files/centos.org/jobs/foreman-forklift-containers-pr-test.yaml
puppet/modules/jenkins_job_builder/files/centos.org/jobs/foreman-forklift-containers-test.yaml
puppet/modules/jenkins_job_builder/files/centos.org/pipelines/lib/ansible.groovy
puppet/modules/jenkins_job_builder/files/centos.org/pipelines/lib/duffy.groovy
puppet/modules/jenkins_job_builder/files/centos.org/pipelines/lib/folderChanged.groovy
puppet/modules/jenkins_job_builder/files/centos.org/pipelines/test/containers.groovy
puppet/modules/jenkins_job_builder/files/centos.org/update_job.sh

The initial job being added is a PR test for Forklift containers.

Add scaffolding for using ci.centos.org and an initial job

---

puppet/modules/redmine/manifests/init.pp

* PostgreSQL tuning
* Handle VCS repo in puppet. This should match the existing situation

Redmine improvements

---

puppet/modules/redmine/manifests/init.pp

b6f49315579aad3650ada19159eef36d7cb92cc8 missed some things.

Redmine fixes

---

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/foreman-hammer-nightly-systest.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/foreman-mysql-nightly-systest.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/foreman-puppet-nightly-systest.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/foreman-puppet-pc1-systest.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/foreman-umask-077-systest.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release_nightly_test_deb.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release_test.yaml

okay, this is properly what we want for the systest jobs!

set 'and' on labels for systest family of jobs

---

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/test_hammer_cli.yaml

Otherwise all branches are built.

Use the correct branches selection for hammer-cli

---

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/foreman.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/deployYum.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/foremanPluginsRelease.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/foremanRelease.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/katelloInstallerNightlyRelease.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/tarballsRelease.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/deploy_web.sh
puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/pkg_generate_source.sh
puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/kafo.sh
puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/proxy.sh
puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_bastion_assets_precompile.sh
puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_develop.sh
puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_hammer_cli.sh
puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_hammer_cli_foreman.sh
puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_hammer_cli_foreman_discovery.sh
puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_hammer_cli_foreman_pull_request.sh
puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_hammer_cli_pull_request.sh
puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_kafo_parsers_master.sh
puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_katello.sh
puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_katello_assets_precompile.sh
puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_katello_javascript.sh
puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_katello_rubocop.sh
puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_plugin.sh
puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_proxy_develop_pr_core.sh
puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_upgrade.sh
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/builders/foreman-plugins-pull-request.yaml

Also silences some RVM installations

Consistently use bundle --jobs=5 --retry=5

---

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/test_katello_javascript.yaml

... because i forgot to set the project-type

test_katello_javascript wasn't updating from JJB

---

puppet/modules/web/files/yum-HEADER.html

* Correct HTML syntax
* Remove F24 mentions
* Link to foreman-release.html via HTTPS
* Mention availability over HTTPS

Update the yum header

---

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/foremanRelease.groovy

3f9a3f015bbd06b2695cb14508968bc87230ce4e introduced a regression in the groovy syntax.

Fix groovy syntax

---

puppet/modules/jenkins_job_builder/files/theforeman.org/unmanaged_jobs.rb

this'll hopefully give people a bit more time to fiddle with test jobs before they get garbage collected

only delete unmanaged jobs at midnight

---

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/rubygemKatelloNightlyRelease.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/build/rubygem-katello-nightly-release.yaml

remove rvm from rubygem-katello-nightly-release

---

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/foreman-discovery-image-publish.sh

This now uses the openstack provider which we've switched to a while
back. We drop the --debug in provision because that leaks API keys.
I haven't tested this yet, but it should be enough.

Correct vagrant in foreman-discovery-image-publish

---

README.md

This is very much a work in progress and I know I forgot many conventions. Please suggest those I forgot :)

[RFC] Document Jenkins Job Naming conventions

---

puppet/modules/scaleway/files/manage_snapshots.rb
puppet/modules/scaleway/manifests/cron.pp
puppet/modules/scaleway/manifests/init.pp

Created by quick edits to local puppet and agent now runs clean.

Scaleway: fixes for issues found at deployment time

---

puppet/modules/redmine/manifests/init.pp

As per comments in #696, this has been stable for a month, so we should update it

redmine: Update HSTS to 6 months

---

puppet/modules/web/manifests/init.pp
puppet/modules/web/templates/web.conf.erb

Also, redirect next version to nightly manual

Update web class for 1.19 manual

---

puppet/modules/slave/manifests/docker.pp

To enable Jenkins slave to run docker

Ensure Jenkins user part of docker group

---

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/plugins/foreman_discovery.yaml

Adding discovery 13 stable branch job

---

puppet/modules/prprocessor/manifests/init.pp

The script wants to close issues so it needs the API key.

Set the Redmine API key for close_inactive.rb

---

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/koji.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/test/rpm_packaging.groovy

not the status of the overall jenkins job

post the real koji status to github

---

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/packaging_test_pull_request_deb.sh
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/scm/foreman-packaging.yaml

This reverts commit adb5642530827412a5a4cdfefe4b02ae4f905c2c.

Revert "Allow free form deb source branch names"

---

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/duffy.groovy

Ansible 2.4 on Duffy does not support yaml output yet

Switch yaml to debug for Ansible on duffy

---

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/foreman-discovery-image-publish.sh

This is for the changes in https://github.com/theforeman/foreman-discovery-image/pull/108
Please feel free to merge as the current configuration does not work at all and I need to replace config manually over and over again when testing this. Thanks! @ekohl

Fix fdi publish vagrant provider

---

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/foremanPluginsRelease.groovy

Provides better visual for internal stages inside parallel steps:

Move foreman plugins release to multi-stage parallel

---

puppet/modules/jenkins_job_builder/files/centos.org/centos_jenkins.ini
puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/infra/updateJobs.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/virtualEnv.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/foreman-infra-jenkins-jobs-update.yml

This job will update the Foreman jobs for ci.centos.org every fifteen minutes.

Add update-job for ci.centos.org jobs

---

puppet/modules/web/manifests/stats.pp

Cleaned up the params a bit too.

Redirect stats dashboard http to https

---

puppet/modules/web/manifests/init.pp

Update web class for 1.20 branching

---

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/obal.groovy

this can have valuable information for debugging

archive the extra vars file

---

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/katelloInstallerNightlyRelease.groovy

since packaging_build_rpm doesn't know how to deal with
`nightly_jenkins_job` and `nightly_jenkins_job_id` parameters anymore

katello-installer-nightly-release - remove triggering of pack_build_rpm

---

.gitmodules
puppet/modules/foreman_debug_rsync/manifests/config.pp

update selinux to 1.6.1

---

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/plugins/foreman_discovery.yaml

Update discovery for version 14.0

---

puppet/modules/jenkins_job_builder/files/centos.org/ansible/jenkins_job.yml
puppet/modules/jenkins_job_builder/files/centos.org/jobs/foreman-ci-centos-simple-test.yml
puppet/modules/jenkins_job_builder/files/centos.org/pipelines/test/simple.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/duffy.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/foremanRelease.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/katello/nightly.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/test/ci_centos_integration_test.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/pipeline/ci-centos-integration-test.yaml

Also add simple test jobs for ci.theforeman.org and ci.centos

Put ci.centos job links on build description

---

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/ansible.groovy

"false ?: true" is always true :/
need to check for null explicitly

fix disabling of archiving of the extra vars file

---

puppet/modules/jenkins_job_builder/files/centos.org/pipelines/lib/foremanCentosJob.groovy
puppet/modules/jenkins_job_builder/files/centos.org/pipelines/test/katello/3.10-upgrade.groovy
puppet/modules/jenkins_job_builder/files/centos.org/pipelines/test/katello/3.10.groovy
puppet/modules/jenkins_job_builder/files/centos.org/pipelines/test/katello/3.8-upgrade.groovy
puppet/modules/jenkins_job_builder/files/centos.org/pipelines/test/katello/3.8.groovy
puppet/modules/jenkins_job_builder/files/centos.org/pipelines/test/katello/3.9-upgrade.groovy
puppet/modules/jenkins_job_builder/files/centos.org/pipelines/test/katello/3.9.groovy
puppet/modules/jenkins_job_builder/files/centos.org/pipelines/test/katelloNightlyTest.groovy
puppet/modules/jenkins_job_builder/files/centos.org/pipelines/test/katelloUpgradeNightly.groovy

these are the required infra changes for https://github.com/theforeman/forklift/pull/880

Simplifying our forklift testing pipeline definitions

---

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release_nightly_test_deb.yaml

This reverts commit c593b80995c1a750d0e7058c426daf24ec52d236.

Revert "Skip Ubuntu tests in release_nightly_test_deb"

---

puppet/modules/web/manifests/init.pp

This should only be merged once we have the 1.21 manual update in theforeman/theforeman.org prepared.

Prepare for 1.21 manual

---

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/foreman.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/rvm.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/test/smart-proxy-develop-test.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/test/test_foreman.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/tests/foreman-develop-test.yaml

This still needs some work such as triggers setup, and addressing comments. However, I am opening this up as testing of it is going well for comments to replace `test_develop`.

Add a pipeline for test_develop

---

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release/foreman-selinux-develop-release.yaml

otherwise obal() does not work properly

add ansible.groovy to foreman-selinux-develop-release

---

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/packaging_test_pull_request_deb.sh

These are the nightly jobs that are now responsible for building tarballs.

Correct the Debian PR tester jobs

---

puppet/modules/jenkins_job_builder/files/centos.org/pipelines/lib/foremanCentosJob.groovy
puppet/modules/jenkins_job_builder/files/centos.org/pipelines/test/katello/devel.groovy

Also fixes the missing archiveArtifacts issue we have seen
Uses https://github.com/theforeman/forklift/pull/920

Use updated devel pipeline

---

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/obal.groovy

obal doesn't support that since a long time [1]
[1] https://github.com/theforeman/obal/commit/45f336f3bc931923f362700869abcb2cdf880b43

don't pass tags to obal

---

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/client/1.20.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/client/1.21.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/client/nightly.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/foreman-rpm.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/tfmROR51.groovy

* 3b7f4b57 Correct tfmROR51 repo location
* 2887651e Correct repo destination for foreman nightly
* 63d93301 Fix client pipelines. In the current version of Jenkins and plugins a stage doesn't guarantee it's ran on the same agent. That means we were cloning and preparing one agent and then running it on the next.

Fix pipelines

---

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/koji.groovy

use the right credentials when submitting koji data to github

---

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/test/test_foreman.groovy

Being tested in https://ci.theforeman.org/blue/organizations/jenkins/foreman-develop-test/detail/foreman-develop-test/7/pipeline

Archive junit test results in foreman-develop-test

---

puppet/spec/defines/web_htpasswd_spec.rb

An old branch I had locally but never pushed.

Add a test for web::htpasswd

---

puppet/modules/redmine/files/git_repos.sh

I'm not 100% sure this improves things, but sometimes we get error mails on on nil values and this should improve the debug options.

Handle nil values

---

puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/test_hammer_cli_foreman_pull_request.sh

Should fix the problem here: https://github.com/theforeman/hammer-cli-foreman/pull/419#issuecomment-483842232

Fix hammer-cli-foreman pull request tests

---

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/plugins/foreman_discovery.yaml

Branch for Discovery 15

---

puppet/modules/web/templates/web.conf.erb

Let's review this first (please carefully read the regexp), once confirmed I
will add more plugins. Then I suggest to merge this and roll it out, then we
can test and finally I can proceed with deleting the content for real.

Custom 404 error

---

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/foreman_infra.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/foreman-deb.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/foreman-rpm.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/katello/nightly.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/luna/nightly.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/test/ci_centos_integration_test.groovy

The goal of this PR is to make it easier to see why a build failed.

Improve discourse notifications

---

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/smart-proxy-plugin-pull-request.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/smart-proxy-plugin.yaml

These tests are failing and the last commit in the project was in 2016.

Remove smart_proxy_abrt tests

---

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/foremanPluginsRelease.groovy

Tested in https://ci.theforeman.org/blue/organizations/jenkins/foreman-plugins-rpm-pipeline/detail/foreman-plugins-rpm-pipeline/118/pipeline

Run plugin rpm pushing in the correct directory

---

puppet/modules/web/manifests/init.pp

The "latest" link is broken, this fixes it.

Latest stable is 1.22

---

puppet/modules/jenkins_master/manifests/init.pp

don't install outdated Jenkins RVM plugin

---

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/foreman_infra.groovy

findAll is not permitted inside the groovy sandbox, minus is.

Replace findAll() with minus(null)

---

puppet/modules/web/manifests/init.pp

Adding redirect for the Foreman 1.23 version.

Update web class for 1.23 version

---

.travis/jjb.sh
puppet/modules/jenkins_job_builder/files/centos.org/ansible/jenkins_job.yml
puppet/modules/jenkins_job_builder/files/centos.org/jobs/foreman-release-test.yml
puppet/modules/jenkins_job_builder/files/centos.org/pipelines/test/foreman/release.groovy
puppet/modules/jenkins_job_builder/files/jenkins-lint.py
puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/foreman_infra.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/test/ci_centos_integration_test.groovy

Split off from https://github.com/theforeman/foreman-infra/pull/992 so I can start testing that part.

Create release test jobs on CentOS CI

---

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/ansible.groovy

otherwise we might end up writing the same file twice in a very parallel
pipeline

add an UUID to the extra vars file we write

---

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/ansible.groovy

This reverts commit 0a10c228d2002cee053e10a2713277fcae9d633d.
This had some weird side effects that I don't fully understand. Reverting until we really need the functionality.

Revert "allow running ansible playbooks in a virtualenv"

---

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/plugins/foreman_discovery.yaml

Disovery 15.1 release

---

puppet/modules/deploy/manifests/init.pp
puppet/modules/web/manifests/init.pp

update foreman_search string

---

puppet/modules/web/manifests/init.pp

we don't differentiate between "latest" and "stable" anymore

drop latest param from the web class

---

puppet/modules/jenkins_job_builder/files/centos.org/jobs/foreman-discovery-image-build.yml
puppet/modules/jenkins_job_builder/files/centos.org/pipelines/foreman-discovery-image-build.groovy

this does add a build job, but does not yet connect it to the release job on ci.tfm.o

add a job to build foreman-discovery-image on ci.centos.org

---

puppet/modules/web/manifests/init.pp
puppet/spec/classes/web_spec.rb

drop the includes again, we use default mods

---

puppet/modules/web/manifests/init.pp

this is needed until
https://github.com/puppetlabs/puppetlabs-apache/pull/1958 is merged and
we have that deployed

explicitly quote expires_default

---

puppet/modules/web/files/yum-robots.txt
puppet/modules/web/manifests/init.pp

this should make search engines ignore nightly repos

add robots.txt to yum.theforeman.org

---

ansible/fastly.yml

this should produce less files

proxy fastly logs via one region

---

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/foreman-discovery-image.groovy

we actually want to publish the artifacts :)

don't run rsync with --dry-run

---

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/foreman-discovery-image.groovy

-a preserves owner, group and permissions, but we want to inherit what's
on the destination server

run rsync with -rlt not -a

---

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/foreman-pipeline.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/foreman-rpm.groovy

also explicitly mash nightly in the nightly pipe

mash rails repo when doing a foreman release

---

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/client.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/pipeline/foreman-release.yaml

also use the helper in client.groovy

include foreman_infra.groovy for plugins pipelines

---

puppet/modules/slave/manifests/init.pp
puppet/spec/classes/slave_spec.rb

These were added a while ago and now we can assume they're all cleaned up.

Remove old ensure => absent resources

---

puppet/modules/jenkins_job_builder/files/centos.org/pipelines/test/foreman/nightly-centos7.groovy

Requires https://github.com/theforeman/forklift/pull/1073
This is probably needed for all install pipelines, but I first want to test this out.

Collect smoker logs in foreman nightly

---

puppet/modules/web/manifests/init.pp

Some overlooks: https://github.com/theforeman/foreman-infra/pull/1200

Fixed docs vhost for web02

---

deploy/config/deploy/yum.rb

this will purge a bit more than we want, but it's safer this way

purge yum repos from the CDN after publishing them

---

deploy/config/deploy/yum.rb
puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/foreman-discovery-image.groovy

properly quote the string inside the awk call

---

deploy/config/deploy/yum.rb

I think it generates wrong URLs, this is to test that
Should be reverted afterwards.

be temporarily verbose when flushing CDN

---

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/test/kafo.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/test_kafo_pull_request.yaml

Please review carefully. This is the first time I convert something to a pipeline :)

Rewrite kafo PR tests to a pipeline

---

koji/foreman-client-mash-split.py

1.20/1.21 is not supported anymore

don't include el8 for 1.22/1.23/1.24

---

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/foreman-pipeline.groovy

don't push rails repo for 2.0 and newer releases

---

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/smart-proxy-plugin-pull-request.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/smart-proxy-plugin.yaml

Currently this repository is tested by Travis but this unifies the testing.

Add dhcp_remote_isc tests

---

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/smart-proxy-plugin-pull-request.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/smart-proxy-plugin.yaml

Currently these are tested in Travis but by standardizing on Jenkins this simplifies maintenance.

Add tests for smart-proxy-{dhcp,dns}-infoblox

---

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/source/smart-proxy.groovy

94efdf57cda7c4b4640558c7dae4a265a54cf255 refactored this file, but left this reference.

Fix foreman_branch reference

---

deploy/config/deploy/yum.rb

repo_instance_path is empty at this stage

use repo_path to figure out which sub folders we need to purge

---

puppet/modules/jenkins_job_builder/files/centos.org/jobs/foreman-upgrade-nightly-test.yml
puppet/modules/jenkins_job_builder/files/centos.org/pipelines/test/foreman/nightly-upgrade-centos7.groovy
puppet/modules/jenkins_job_builder/files/centos.org/pipelines/test/foreman/nightly-upgrade-debian10.groovy
puppet/modules/jenkins_job_builder/files/centos.org/pipelines/test/foreman/nightly-upgrade-ubuntu1804.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/foreman-deb.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/foreman-rpm.groovy

This depends on https://github.com/theforeman/forklift/pull/1134 and https://github.com/theforeman/forklift/pull/1135

Add Foreman nightly upgrade pipelines

---

koji/flatten-el8/README.md
koji/flatten-el8/koji-ansible/inventory/inventory
koji/flatten-el8/koji-ansible/master.yaml
koji/flatten-el8/koji-ansible/roles/grobisplitter/README.txt
koji/flatten-el8/koji-ansible/roles/grobisplitter/files/rhel8-split.cron
koji/flatten-el8/koji-ansible/roles/grobisplitter/files/rhel8-split.sh
koji/flatten-el8/koji-ansible/roles/grobisplitter/files/splitter.py
koji/flatten-el8/koji-ansible/roles/grobisplitter/tasks/main.yml
koji/flatten-el8/script.sh
koji/flatten-el8/test.sh

Note:  grobisplitter role is taken almost verbatim from fedora-ansible folder.  Small modifications have been made to fit our environment

Current state of process running to update koji's flattened el8 repo

---

puppet/modules/secure_ssh/manifests/receiver_setup.pp
puppet/modules/web/manifests/vhost.pp
puppet/modules/web/manifests/vhost/stagingdeb.pp

These are regressions that snuck in and showed up in Puppet noop.

Fixes for the web profile

---

puppet/modules/jenkins_job_builder/files/centos.org/jobs/foreman-nightly-test.yml
puppet/modules/jenkins_job_builder/files/centos.org/pipelines/test/foreman/nightly-centos8.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/foreman-rpm.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/vars/foreman/nightly.groovy

I will move this out of draft status once it is passing locally.

Add EL8 to Foreman nightly pipeline

---

puppet/modules/slave/manifests/postgresql.pp

educated copy of #1285 and #1307 for the `debversion`-extension

Add pg-debversion package to unit test slaves

---

puppet/modules/redmine/files/git_repos.sh

By introducing a wrapper function that silences the deprecation warnings, my inbox should be a lot more quiet. The proper solution is to upgrade Redmine but that's on the roadmap.

Silence deprecation warnings from Redmine

---

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/plugins/foreman_remote_execution.yaml

This reverts commit 4d1892816c3532a582110fae9098f9bd2fff3242.

Put back REX build test job

---

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/plugins/foreman_discovery.yaml

Add discovery 16.1 branch

---

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/plugins/foreman_bootdisk.yaml

SSIA I hope I got it right this time

Add 17.0-stable bootdisk branch

---

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/packaging_build_deb_coreproject.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/packaging_build_deb_dependency.yaml

Also make sure we don't build 2.2 on arm or focal.

Drop stretch and xenial from packaging pipelines

---

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/release.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/debian/stage_packages.sh
puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/debian/stage_packages_dependency.sh
puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/debian/stage_packages_plugin.sh

note: should not be merged before 2.2 RC1 is out.

deploy deb packages to old and new web host

---

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/infra/updateJobs.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/virtualEnv.groovy

and don't change directory to ${path} before executing stuff in the venv

create the venv in ${path} instead of ${path}/venv

---

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/test/rpm_packaging.groovy

pulpcore has no rpm/develop that we pick from.

verify version/release for all pulpcore branches

---

docs/redmine.md

Replaces:
* https://projects.theforeman.org/projects/foreman/wiki/Redmine

Add Redmine docs

---

puppet/modules/freight/templates/cron.erb

This reverts commit 5b3037739b6f46f3847711c17a6bf2cffaf1a69f.
This wiped more nightly bits than I wanted.

Revert "remove all user debs after 7 days"

---

docs/koji.md

Replaces:
* https://projects.theforeman.org/projects/foreman/wiki/Koji
* https://projects.theforeman.org/projects/foreman/wiki/KojiBuilderSetup
* https://projects.theforeman.org/projects/foreman/wiki/KojiSetup
@pcreech I am sure some of this is out of date, or we may not want to include at all. And this may not capture everything newer that we've done.
I did some clean up but left anything I was unsure about to allow review and guide the direction.

Add Koji docs

---

docs/jenkins.md

Replaces:
* https://projects.theforeman.org/projects/foreman/wiki/Jenkins
This one is a bit rough still since it covers Jenkins and jobs. I'm going to split out anything job related to it's down document.

Add Jenkins docs

---

koji/collection-mash-split.py

Foreman 2.3 mash updates

---

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/vars/katello-master-release.groovy
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release/package/hammer-cli-katello-master-package-release.yaml
puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/release/package/katello-master-package-release.yaml

otherwise GHPRB doesn't trigger correctly

use Katello instead of katello in git properties

---

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/pipeline/foreman-nightly-deb-pipeline.yaml

otherwise foreman_version is undefined

add nightly.groovy to debian nightly pipeline

---

puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/plugins/hammer-cli-foreman-kubevirt.yaml

This is actully a hammer test and not a Foreman plugin test.

Remove hammer-cli-foreman-kubevirt testing

---

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/deploy/website.groovy

this will be later used for cache invalidation

add structured changeg-logging to website deploy

---

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/lib/obal.groovy

don't include obal/obsah changelogs in jobs

---

puppet/modules/jenkins_job_builder/files/centos.org/jobs/katello-pipelines.yml

follow up for
https://github.com/theforeman/foreman-infra/pull/1535

also drop katello-devel from ci.centos.org

---

puppet/modules/jenkins_job_builder/files/centos.org/pipelines/lib/pipelines.groovy

See: https://github.com/theforeman/forklift/pull/1250

Update box names to shortened pipeline version

---

puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/pipelines/plugins-pipeline.groovy

the plugins don't affect the version anyways

don't expect version in plugins pipe

---

Vagrantfile
puppet/modules/slave/files/db/mysql
puppet/modules/slave/files/db/sqlite3
puppet/modules/slave/manifests/db_config.pp
puppet/modules/slave/manifests/init.pp
puppet/modules/slave/manifests/mysql.pp
puppet/modules/slave/manifests/packaging/rpm.pp
puppet/modules/slave/manifests/postgresql.pp
vagrant/manifests/default.pp

* Drop MySQL from nodes
* Update RVM form 1.29.9 to 1.29.10
* Ordering fixes
* Experimental conditionals for EL8 nodes
* Vagrant config to allow spinning up nodes

Jenkins node updates

---

puppet/modules/slave/manifests/init.pp

Install qpid-proton-cpp-devel on Jenkins nodes

---

puppet/modules/slave/files/pbuilder_D80no-man-db-rebuild
puppet/modules/slave/manifests/pbuilder_setup.pp

it takes long and is utterly useless

don't update man-db in the chroot

---

koji/README
koji/playbooks/external_repos.yml
koji/requirements.yml
koji/vars/external_repos.yml

Note, I have not tried to clean anything up here but to first capture what already exists.

Add management of Koji external repositories

---

.github/workflows/main.yml
puppet/Rakefile
puppet/modules/jenkins_job_builder/manifests/config.pp
puppet/modules/secure_ssh/manifests/receiver_setup.pp
puppet/modules/slave/manifests/packaging/debian.pp
puppet/modules/web/manifests/vhost/yum.pp
puppet/spec/spec_helper.rb

This action is maintained by the Ruby developers. It has built in caching and bundler handling.

Use ruby/setup-ruby Github Action + Puppet Lint fix

---

puppet/modules/slave/templates/pbuilder_f70.erb

use cat, not echo to load the key

---

koji/playbooks/users.yml
koji/vars/users.yml

Follow on to https://github.com/theforeman/foreman-infra/pull/1625 once the structure there is agreed to to disable inactive Koji users.

Disable koji users

---

koji/vars/external_repos.yml

This will help enable a more controlled centos 8 build environment

Add el8 module repos

---

puppet/modules/slave/manifests/init.pp

This is a preparation for another PR.

Install JQ and mark JSON.sh as the old implementation

---

puppet/modules/slave/templates/pbuilder_F60addforemanrepo.erb

this allows pbuilder update to work again

only add foreman repo if version is set

---

puppet/modules/profiles/manifests/jenkins/node.pp

we did that in the jenkins node class, but not in the profile

enable unittests only on RH family

---

puppet/modules/deploy/files/script.sh

Fixes: fa1f88953681dd9033c90fd2c514c1fc73ebe3d7

Fix typo in variable name

---

puppet/modules/slave/manifests/init.pp

install curl on all jenkins nodes

---

koji/collection-mash-split.py

This parameter was not used and callers weren't passing it in.
Fixes: 3f4ee09d908dc7f947f451cad8c3ba68d18157d6

Fix mashing script after get_from_git refactor

---

Vagrantfile
puppet/modules/awstats/manifests/init.pp
puppet/modules/web/manifests/vhost/yum.pp

See individual commits for details. I only verified I could run `vagrant up web` after changing the box to CentOS Stream 8.

Ensure the web profile works on EL8

---

puppet/modules/web/files/deploy-yumrepo.sh

we need the metadata as generated on koji for the modules

don't exclude metadata when syncing repo from koji

---

puppet/modules/slave/manifests/packaging/debian.pp

so that we get latest ubuntu and debian releases too

always install debootstrap from backports

---

puppet/modules/web/files/deploy-yumrepo.sh

test chockes if there are more than one file found

use ls instead of test

---

docs/index.md
docs/virt.md
mkdocs.yml

Document Virtualization host at Conova

---

puppet/modules/slave/manifests/unittests.pp

psych stopped vendoring it and this breaks several tests

ensure libyaml-devel is installed

---

docs/secrets.md

This is based on what's in theforeman-rel-eng, but also adds some background.

Document secret storage

---

Vagrantfile
docs/backups.md
mkdocs.yml
puppet/Puppetfile
puppet/data/common.yaml
puppet/manifests/site.pp
puppet/modules/profiles/manifests/backup/receiver.pp
puppet/modules/profiles/manifests/backup/receiver/target.pp
puppet/modules/profiles/manifests/backup/sender.pp
puppet/modules/profiles/manifests/redmine.pp
vagrant/manifests/default.pp

This introduces backup profiles using Restic. There's both a sender and a receiver profile.
Right now docs are missing and I'm still working on it, but sending the work for while I continue.

Add backups using Restic

---

puppet/data/common.yaml
puppet/data/osfamily/RedHat-7.yaml
puppet/modules/profiles/manifests/backup/sender.pp
puppet/spec/classes/profiles_redmine_spec.rb

This has the benefit that in tests you can declare the restic class to set a password. With that in place, a test for the redmine profile module is added as well.

Move all backup parameter to Hiera

---

puppet/manifests/site.pp
puppet/modules/profiles/manifests/discourse.pp

This currently doesn't manage Docker and the app checkout itself, but at least sets up the backup.

Add a profile for discourse

---

puppet/modules/slave/manifests/rvm.pp

See https://github.com/theforeman/foreman-infra/pull/1850#issuecomment-1644099976 for details

Set back Ruby back to 3.0.4 and 3.1.3 due to old GCC

---

puppet/modules/slave/templates/copr.erb

Fixes: f1934f33bcdb ("Remove copr config")

Remove unused copr config file template

---

puppet/manifests/site.pp

This reverts commit 3275386c7d1e0226a288d3cf2d492066984f0dba.

Revert "don't apply redmine profile for node1.conova for now"

---

puppet/modules/slave/manifests/packaging/rpm.pp

By now all nodes have applied this.

Remove tito ensure absent

---

Vagrantfile

This is what we aim for in our production and more and more boxes are migrated.

Change the default Vagrant box to centos/stream9

---

puppet/modules/redmine/files/git_repos.sh

the /redmine_repos endpoint has to go away

consume redmine repos directly from prprocessor config

---

puppet/manifests/site.pp

puppet-side of cleanup is done

completely remove backup receiver from puppet01

---

puppet/data/osfamily/RedHat-9.yaml

master now contains our live code

drop the branch override for redmine on el9

---

puppet/modules/slave/manifests/unittests.pp

https://github.com/voxpupuli/puppet-nodejs/blob/master/manifests/install.pp#L47

Ensure npm and nodejs are not removed on Jenkins node

---

koji/collection-mash-split.py

Fixes: 815dc6a1f321f0165133ae04fe420d9d3473de0c

properly pass collection name into handle_comps

---

puppet/modules/slave/manifests/packaging/rpm.pp

Current failure:
```
16:57:02  + ./build_stage_repository candlepin nightly el8
16:57:02  Traceback (most recent call last):
16:57:02    File "./build_stage_repository", line 7, in <module>
16:57:02      import yaml
16:57:02  ModuleNotFoundError: No module named 'yaml'
```

Install python3-pyyaml for theforeman-rel-eng scripts

---

puppet/modules/profiles/manifests/web.pp

Now that Foreman 3.10.0 is GA we can update this to 3.10.

Update stable version to 3.10

---

puppet/modules/web/files/deploy-yumrepo.sh

fixes for https://github.com/theforeman/foreman-infra/pull/2040

local rsync fixes

---

puppet/modules/jenkins_node/manifests/unittests.pp

we don't have katello-agent/qpid anymore

don't install qpid-proton-cpp-devel

---

puppet/spec/spec_helper.rb

This reverts commit b27a41a6681863142fe19f3375192890eec34fd9.

Revert "Stop testing for Debian 12 for now"

---

puppet/modules/jenkins_node/templates/npm_cleaner.sh.erb

seems nuking parts breaks it :shrug:

nuke the whole npm cache, not parts of it

---

puppet/modules/freight/manifests/user.pp
puppet/modules/profiles/manifests/web.pp
puppet/modules/web/manifests/vhost/deb.pp

relying on the variable from the profile is a bad idea

pass $stable to freight::user directly

---

puppet/data/common.yaml

Fixes: 0a2b93c6d62e730497836b7f2f3a28892a5bcfaf

also pass rsync usernames to stagingyum

---

vagrant/hiera.yaml

Fixes: 674f4c13ec835a2857e7a04b0d6c1d67d15e382f

load internal.yaml for vagrant too

---

puppet/Gemfile
puppet/Puppetfile
puppet/data/internal.yaml
puppet/modules/profiles/manifests/base.pp

replace claranet/timezone with puppet/systemd

---

Vagrantfile

- **drop unused el7 and el8 jenkins nodes**
- **update website box to el9**
- **update backup box to el9**

update vagrant boxes

---

puppet/modules/profiles/templates/base/alloy-config.epp

Fixes: 1bd990b10225ca4490b2d4039bdd577a2461f85a

make alloy config indentation cleaner

---

puppet/modules/profiles/files/base/restic-prometheus-exporter.py

Fixes: a4cda8f34f5b9a8e00de5a6f32f96fe6981f86fd

correct walrus operator in restic prometheus exporter

---

puppet/modules/profiles/manifests/base/monitoring.pp

Fixes: a4cda8f34f5b9a8e00de5a6f32f96fe6981f86fd

correct permissions on /var/lib/prometheus/node-exporter

---

docs/monitoring.md

- **add backup alert**
- **add direct links to dashboards**

more monitoring doc

---

puppet/modules/jenkins_node/files/pbuilder_F66-add-nodesource-nodistro-repos
puppet/modules/jenkins_node/manifests/packaging/debian.pp
puppet/spec/classes/jenkins_node_spec.rb

https://github.com/theforeman/foreman-infra/pull/2262 with review comments addressed

Update Debian/Ubuntu to Node 22 for 3.16+

---

puppet/modules/openvox_repo/manifests/apt.pp
puppet/modules/openvox_repo/manifests/init.pp
puppet/modules/openvox_repo/manifests/purge_puppet.pp
puppet/modules/openvox_repo/manifests/yum.pp

add module to configure openvox repo

---

puppet/modules/profiles/manifests/puppetserver.pp

includes https://github.com/theforeman/foreman-infra/pull/2305

switch puppetserver profile to openvox

---

puppet/modules/profiles/manifests/base.pp
puppet/modules/profiles/manifests/puppetserver.pp

switch base profile to openvox
